### ISSUE TITLE
Lack of shaman totem UI

### ISSUE THREAD

**Issue by Phawkesy** [Helios-Empire/Helios-Tracker#10]
There seems to be a lack of UI for the totems that shows which totems are down at any one time. This is kinda annoying because you cant click on them to make them despawn, so for eg  searing totem keeps pulling guys if there are guys in range.

**Comment by HEGladios** [comment]
Got this working locally. After some good tests we'll be able to add it to the live server soon!

**Comment by dikkedeur** [comment]
FIXED
