### ISSUE TITLE
NPC: Mob abilites (Nagrand)

### ISSUE THREAD

**Issue by scottiedog321** [Helios-Empire/Helios-Tracker#100]
Multiple types of mobs do not seem to be using their abilities. The most noticeable are the casters:
Boulderfist Mage: http://www.wowhead.com/npc=17137/boulderfist-mage#abilities
Boulderfist Mystic: http://www.wowhead.com/npc=17135/boulderfist-mystic#abilities

There maybe others as well.

**Comment by dikkedeur** [comment]
Fixed after next server restart or core update.
