### ISSUE TITLE
Bugged Quest in Hellfire Peninsula: Disrupt Their Reinforcements

### ISSUE THREAD

**Issue by Jucamilo** [Helios-Empire/Helios-Tracker#106]
After you get "Demonic Rune Stone x4", now you can use the "to'arch's primers", but the problem is when you try to use it in a port, it says "Invalid target" and i tried in both ports (Xilus and Kruul).

![wowscrnshot_091415_115811](https://cloud.githubusercontent.com/assets/14279615/9856690/d0d029ae-5adb-11e5-8b91-6046a6b819d9.jpg)

I tried without using stealth too.

**Comment by HEGladios** [comment]
I think this works if you move to the middle of the object and then use it. Have you tried that?

**Comment by Jucamilo** [comment]
I will, sec.

**Comment by Jucamilo** [comment]
Yeah! that's right, no matter if you are in the range, you have to go in and used from the inside and it will work. thank you :)
