### ISSUE TITLE
Quest [Infiltrating Dragonmaw Fortress] in Shadowmoonvalley doesn't work

### ISSUE THREAD

**Issue by Inyu** [Helios-Empire/Helios-Tracker#107]
You have to kill 15Dragonmaw Orcs but neither counts towards the completion of the quest.

**Comment by dikkedeur** [comment]
interesting, since when i look on how it should be, there should be various orcs that can count to it.
will take a look at how this works.

**Comment by dikkedeur** [comment]
tested it, it works
