### ISSUE TITLE
Arcane Disturbances

### ISSUE THREAD

**Issue by ghost** [Helios-Empire/Helios-Tracker#108]
I'm unable to use the item for the quest at the underground pond reading, the well reading worked fine, but the pond does not. I receive the following no matter where i stand in the pond: "Requires underground water source." Yes it is the correct spot since I even looked up online to see where the two spots are, is anyone else having an issue with the pond spot as well?

**Comment by dikkedeur** [comment]
![schermafbeelding 2015-10-14 om 19 56 44](https://cloud.githubusercontent.com/assets/11842306/10492795/2832b2a4-72ae-11e5-845e-12600c054c42.png)

thats the spot, kinda...

![schermafbeelding 2015-10-14 om 19 56 55](https://cloud.githubusercontent.com/assets/11842306/10492808/344b0668-72ae-11e5-83b7-77d54790963c.png)

then you have this

![schermafbeelding 2015-10-14 om 19 59 06](https://cloud.githubusercontent.com/assets/11842306/10492816/3d3d7076-72ae-11e5-9956-b43a5bb04bc9.png)

the next one :+1: 

![schermafbeelding 2015-10-14 om 19 59 14](https://cloud.githubusercontent.com/assets/11842306/10492828/47e22364-72ae-11e5-99f6-bdaaeada9f7f.png)

JOB DONE!!!
