### ISSUE TITLE
Night Elf Corpses Attacking NPC's in An' telas

### ISSUE THREAD

**Issue by MissSnowy** [Helios-Empire/Helios-Tracker#109]
While traveling through GhostLands I was doing the quest that took me up to An'telas and noticed that the Night Elf Corpses were attacking the friendly NPC's there.

They didn't attack me unless I attacked them though.

![wowscrnshot_101015_163323](https://cloud.githubusercontent.com/assets/15068526/10413218/b34ca432-6f6e-11e5-9bae-8e7f0d7d06fe.jpg)

**Comment by dikkedeur** [comment]
more funny note, he should be dead, after all its a corpse :P

i will look into this one.

**Comment by dikkedeur** [comment]
fixed on next core restart
