### ISSUE TITLE
Quest [Teron Gorefiend, I am...] in Shadowmoonvalley is bugged

### ISSUE THREAD

**Issue by Inyu** [Helios-Empire/Helios-Tracker#110]
Teron should "posses" you and you get new abilitys to kill the npc which spawns.
Atm its just the dialogue and nothing else happens

**Comment by LoveYourBody** [comment]
This might help https://github.com/TrinityCore/TrinityCore/issues/14643

**Comment by dikkedeur** [comment]
i tested the script on our dev server here at my home, but there are problems with it, sai is implemented but the spellsystem that should do the magic trick doesnt, i have forwarded the fix, but it needs total rewrite of the spellsystem.
so for now i think it will not be fixed anytime soon, but you never know.

**Comment by HEGladios** [comment]
Added workaround for this quest, will be active after next core update.
