### ISSUE TITLE
Swimming Mobs

### ISSUE THREAD

**Issue by MissSnowy** [Helios-Empire/Helios-Tracker#111]
While traveling by the river near the Dead Scar as well as in Zeb'Nowa, some of the mobs are not walking around, but they are swimming around.

![wowscrnshot_101415_185037](https://cloud.githubusercontent.com/assets/15068526/10501368/b4e366a8-72ae-11e5-9f77-621d1695e464.jpg)

**Comment by dikkedeur** [comment]
man i have been discussing this for some time, there is a hacky fix.. it does work.. but its not a final fix..
for now it will work...
are there other mobs that have this problem??
if so then names would be great to have.

**Comment by dikkedeur** [comment]
![schermafbeelding 2015-12-05 om 14 12 12](https://cloud.githubusercontent.com/assets/11842306/11607922/3f12d3b2-9b5a-11e5-8422-61e1b49e6958.png)

**Comment by dikkedeur** [comment]
proof that it looks better now, but meh we need to find out how this comes, since the way i fix it now is messing with so many flags lawl :P

**Comment by dikkedeur** [comment]
this is fixed :+1:
