### ISSUE TITLE
Animal Skills

### ISSUE THREAD

**Issue by MissSnowy** [Helios-Empire/Helios-Tracker#114]
Natural Armor and Great Fortitude are not adding their values to the Animal's Stats

**Comment by HEGladios** [comment]
It seems to be working for me.
Remember, you have to get the spells from the Pet Trainer first. After that you can use Beast Training from your spellbook to teach your current pet those spells. (requires pet training points)

**Comment by dikkedeur** [comment]
@MissSnowy have you followed @HEGladios  direction if this is still happening? can you test his suggestions?

**Comment by MissSnowy** [comment]
this can be closed as far as Im concerned.. was having a total noob moment
