### ISSUE TITLE
In Use Glitch

### ISSUE THREAD

**Issue by MissSnowy** [Helios-Empire/Helios-Tracker#117]
From time to time this little glitch pops up on Mining Nodes and from various interactive quest items like:

Tomber's Supplies and the little mounds of mud to get the water amulet's.

It will start to gather the item and mess up and then say it's being used when it's not.

**Comment by dikkedeur** [comment]
can you please retest if this still occurs??
it might be fixed in the latest core revision

**Comment by MissSnowy** [comment]
So far everything seems to be working fine

**Comment by dikkedeur** [comment]
thanks for your response @MissSnowy
