### ISSUE TITLE
Skinning Glitch

### ISSUE THREAD

**Issue by MissSnowy** [Helios-Empire/Helios-Tracker#118]
Sometimes on Mobs that can be skinned.. it doesn't allowed the mob to be skinned.

**Comment by dikkedeur** [comment]
do you have more information, like what creatures is it? is it always on the same mob? is it totally random??

**Comment by MissSnowy** [comment]
It seems to happen randomly.. but seen it more with the various cat mobs.

**Comment by dikkedeur** [comment]
can you retest now, it might be fixed due last core revision that influence all spells related things.

**Comment by MissSnowy** [comment]
since the latest update.. this hasn't been happening. I think this one can be closed now.

**Comment by dikkedeur** [comment]
thanks for the feedback @MissSnowy  :+1:
