### ISSUE TITLE
General Timing

### ISSUE THREAD

**Issue by MissSnowy** [Helios-Empire/Helios-Tracker#119]
Something I have noticed just recently.. everything seems to be off in regards to the timing of things.

Like things are taking half the time that they should.

An example that I can think of:

Level 2 FireBall has a 2 second casting time. and when the casting bar comes up.. the spell goes off at around the E and B in Fireball instead of going all the way across.

I have also noticed this same timing being off in opening chests, and even skinning.

I was thinking that maybe it was a latency thing.. but after looking at it in game. It was 123 MS and that's about normal for me and I haven't noticed the timing being off like this before.

**Comment by dikkedeur** [comment]
yes i know and should be fixed in next core update, i have had a blast while testing this.
so enjoy while you can and thanks for the report.

hope you are okay that i already close this issue then.

**Comment by MissSnowy** [comment]
I'm just glad to know that the team is aware of this issue and working on it :)

**Comment by dikkedeur** [comment]
yeah i was aware of it yesterday already, so a fix has been pushed to the repo i need only to ask gladios to get the merge errors out of the pull so that i can update the core.
