### ISSUE TITLE
The abyssal Shelf again

### ISSUE THREAD

**Issue by ghost** [Helios-Empire/Helios-Tracker#121]
It seems the quest Mission: The Abyssal Shelf broke again, I've attempted it on two different characters with setting reduced. (off chance it was my end causing the issue) When i fly toward the location in order to bomb the targets they all disappear and when attempting to use item says i'm to far away. If i had to guess the issue could be due to the wind rider i'm experiencing because when i logout mid flight it instantly teleports me to the npc wing commander brack as if i never left.

**Comment by dikkedeur** [comment]
it might be due that problem with those cells, i keep my hands on that part, since after that change some things dont work as they should.

**Comment by dikkedeur** [comment]
fixed now
