### ISSUE TITLE
Garrick's Head!

### ISSUE THREAD

**Issue by LoveYourBody** [Helios-Empire/Helios-Tracker#124]
Basicly, you can't attack this mob with abilities nor you can loot him after killing him with auto attacks.
https://sc-cdn.scaleengine.net/i/679b3e61ae3bf2c3dff3604f08c58ea4.png

**Comment by dikkedeur** [comment]
i just tested this whole quest.
i had no problem as mage using my fireball or autoattack garrick.
also after he died i was able to look eveyrhting form him including the quest item.

so i cant reproduce this bug...
