### ISSUE TITLE
Administering the Salve

### ISSUE THREAD

**Issue by ghost** [Helios-Empire/Helios-Tracker#125]
Did this quest today and noticed that you can use the quest item "healing salve" on the same orc since it doesn't change his state after use,  nothing major. the quest can be finished but a possible issue in regards to how it worked in retail.

**Comment by dikkedeur** [comment]
i will look on this one.
thanks for letting us know.

**Comment by dikkedeur** [comment]
fixed in next core update, thanks for the report.
