### ISSUE TITLE
Poor Mordenai, If only he were real

### ISSUE THREAD

**Issue by ghost** [Helios-Empire/Helios-Tracker#127]
So the quest npc mordenai that can be found wandering the netherwing fields in shadowmoon valley, has a tendency to get killed while enjoying the atmosphere of his surrounding.  Making it difficult for the player to progress in his chain, since now we have to wait for a respawn. I'm unsure if this is suppose to happen but it does get annoying to have to wait for the respawn when he might die again upon respawn if we're not around.

**Comment by dikkedeur** [comment]
hmm this might be a easy fix, since we can make him immune to attacks to other creatures.. at least thats my idea and it might not be blizzlike, but a dead npc all the time is also not a blizzlike feature ^^
this one is MINE!

**Comment by dikkedeur** [comment]
fixed in next core update.
