### ISSUE TITLE
Meeting at the blackwing coven

### ISSUE THREAD

**Issue by ghost** [Helios-Empire/Helios-Tracker#129]
Attempted the dialog with two different set of costumes sadly could not get a quest update on either attempts during their 3 min period. Everything seems to be working except no auto update of when you do the meeting itself with the npc, which is where it is broken for me, killed him once in an attempt to reset him but no luck either.

**Comment by dikkedeur** [comment]
will try to make a fix for it

**Comment by ghost** [comment]
no problem, i'm just currently attempting any quests i can do solo to assist with possible bugs, so you can have a clipboard of hopeful fixes. If your unable to get to them right away.

**Comment by dikkedeur** [comment]
fixed at next core restart/update, please retest then the fix comes from TC, havent got time to full test it

**Comment by dikkedeur** [comment]
it was not fixed yet, we still missed alot of sniffed data, that is now resolved and i made a fix that is now in our repo.
so in next core update it will be fixed and working as it should... sorry for the delay
