### ISSUE TITLE
Rogue Poison quest

### ISSUE THREAD

**Issue by Kiszh** [Helios-Empire/Helios-Tracker#13]
On horde you can't even complete "Deep Cover" the NPC simply gives you nothing, making it impossible to obtain poisons, which is completely gamebreaking as a rogue.

**Comment by HEGladios** [comment]
This quest is working just fine.
When the tower is in sight, use the Flare Gun to signal your arrival to Taskmaster Fizzule. Fire off TWO flares, then approach Taskmaster Fizzule and perform the Shattered /Salute.

These actions must be performed in the correct order, as Fizzule will attack and terminate any person he does not recognize.
