### ISSUE TITLE
Bloodscalp Scavenger Rage Bug

### ISSUE THREAD

**Issue by MissSnowy** [Helios-Empire/Helios-Tracker#130]
The Bloodscalp Scavenger's in Stranglethorn Vale when they enter their rage state. It keeps triggering until they are dead. Like someone turning on and off a flashlight really really really fast.

**Comment by dikkedeur** [comment]
time to move this npc from EventAi to Smartai i assume :P

**Comment by dikkedeur** [comment]
lol timer was set to 0, is now set to 120 since its 2 minute buff, although i think within that time you should have killed it.
will be fixed in next core update.. please then retest as well since this was not tested, i just made the fix.
