### ISSUE TITLE
Haunted Bug

### ISSUE THREAD

**Issue by MissSnowy** [Helios-Empire/Helios-Tracker#131]
![wow](https://cloud.githubusercontent.com/assets/15068526/12530498/1a5ee4e0-c1af-11e5-9cca-7609f094d9cd.png)

They just keep respawning over and over.

Talk about life of the party.

**Comment by dikkedeur** [comment]
just for my information, there is a npc haunting spirit that when it dies respawns within a short period of time???

**Comment by MissSnowy** [comment]
The Haunted Servitor's places it on you.

This might help more.

http://wow.gamepedia.com/Haunted_Servitor

I'm guessing they cast Haunting Spirits

**Comment by dikkedeur** [comment]
will be fixed next core update, i moved the eventai to smartai, hopefully that works better when it comes to timing with spells etc.
