### ISSUE TITLE
Hemathion bugs

### ISSUE THREAD

**Issue by Tweaklol** [Helios-Empire/Helios-Tracker#132]
Invald target rare mob sty in ogrila  in Blades adge mountain

**Comment by dikkedeur** [comment]
sorry what do you mean?? you cant target the mob? or do you get an error whats the name of it ?

**Comment by Tweaklol** [comment]
cant attack invalid target but he hits me

**Comment by Tweaklol** [comment]
Hemathion is the name

**Comment by dikkedeur** [comment]
will be fixed in next core update.
