### ISSUE TITLE
group bug

### ISSUE THREAD

**Issue by Tweaklol** [Helios-Empire/Helios-Tracker#133]
the point on worldmap where groupmembers stay dont move. its always on the start position from invite

**Comment by Tweaklol** [comment]
now its not only the the worldmap point . sometimes my mate leave my screen he stay on the same spot and run without moving on this place. but only on my screen he still moving.... i cant see him them cause his model stucks on the 1 place....   sry may english sucks hard i hope you understand what i try to tell you

**Comment by HEGladios** [comment]
Thanks for your report, we'll need to do some testing to find out what causes this issue to occur.

**Comment by Classic-WoW** [comment]
One of my addons enables you to see guildmates (who apperantly share the addon) on the worldmap. I will look more into this once im home.

**Comment by HEGladios** [comment]
This seems to happen when someone runs out of your vision range, they will appear stuck until you meet up with them again.
Feels like some issue with update calls.

**Comment by HEGladios** [comment]
Fixed in next core update.
