### ISSUE TITLE
the ring of blood : the final Challenge   ( Nagrand)

### ISSUE THREAD

**Issue by Tweaklol** [Helios-Empire/Helios-Tracker#138]
The last quest mob in the arena in Nagrand is friendly and cannot be attacked we try it with ally and with horde. he is freindly to both.

**Comment by dikkedeur** [comment]
do you have an npc id?

**Comment by Tweaklol** [comment]
dont no how to get the id ...   mogor   is the name of the mob

**Comment by dikkedeur** [comment]
simple, go to wowhead.com then search for the name of the mob..
then you get a site where you see him.

http://wowhead.com/?npc=18069
the id is then 18069

**Comment by Tweaklol** [comment]
okay now i know it for the next time :)

**Comment by dikkedeur** [comment]
will propably be fixed in next core update, converted the whole questline of ring of blood to sai
