### ISSUE TITLE
The Affray

### ISSUE THREAD

**Issue by ghost** [Helios-Empire/Helios-Tracker#140]
I've heard some people were able to complete this quest for warriors but i've attempted it 4 times in last 2 days to no luck. In order to get berserker stance we have to complete it but basically the mob we have to kill comes out friendly and stays that way until the timer goes away and he despawns.

**Comment by dikkedeur** [comment]
is that big will??

**Comment by dikkedeur** [comment]
i must say i tested this multiple times and didnt encounter this problem.. but will retest it again

**Comment by dikkedeur** [comment]
fixed in next core update, we found it already :+1:
