### ISSUE TITLE
Quest "Battle of the Crimson Watch" bugged

### ISSUE THREAD

**Issue by Inyu** [Helios-Empire/Helios-Tracker#141]
We did that quest today and after we wanted to do it a second time it wouldnt start again.
i completed it the first time but as soon as i went down the stairs my quest got marked as faile too.

**Comment by dikkedeur** [comment]
as far as i know the quest is NOT repeatable and you can only do it once, i did test this on dev server same core and database, and all works for me...
i can do it and complete it after the last wave.

**Comment by Inyu** [comment]
i completed it but after going down the stairs it went from complete to failed.
dont know if u can do something against that.
would be awesome tho^^

**Comment by dikkedeur** [comment]
i did the quest, didnt have that quest failed, since it was done..
i cant reproduce it like you say... 
i went down the stairs killed more mobs went to shattrath turned the quest in

**Comment by Inyu** [comment]
hmm some of my mates died during the fight and then ran back which resulted in them failing.
i kited him through that time and after they came back we finished it
maybe that was the cause?

**Comment by dikkedeur** [comment]
might be, remember that i test it alone :P  gm task ftw
