### ISSUE TITLE
Arena gear

### ISSUE THREAD

**Issue by Inyu** [Helios-Empire/Helios-Tracker#142]
i dont know if its intentional or not but current we can buy the s4 gear with arena points.

**Comment by HEGladios** [comment]
Hi, could you tell me where the s4 gear can be bought? (npc name/ID, locations, etc)
If it's a very specific vendor then I might have missed it.

So no, you are not supposed to be able to buy that :D

**Comment by Inyu** [comment]
its the one in nagrand
have to run back and get the name

**Comment by HEGladios** [comment]
Thanks for your report!
I forgot to delete these apparently. They have been removed.
