### ISSUE TITLE
Quest: The Fare of Lar'korwi

### ISSUE THREAD

**Issue by winterss** [Helios-Empire/Helios-Tracker#143]
Quests needs you to 'loot' a carcass in Un'Goro crater, 
however you dont recieve loot when you interact with the carcass, and when you try again, it sais "this is already being looted"

quest cannot be completed.

**Comment by dikkedeur** [comment]
was the bug not present??

**Comment by winterss** [comment]
Apparently it works when you stand in the right position.. TheWitcher
showed me last night..
Op 3-feb.-2016 23:05 schreef "Dikkedeur" notifications@github.com:
