### ISSUE TITLE
Druid cat form

### ISSUE THREAD

**Issue by winterss** [Helios-Empire/Helios-Tracker#144]
not usable indoors 
(yes i know you already know about it, just tought i post it, since its not on here yet)

**Comment by HEGladios** [comment]
Think this has to do with the Feral Swiftness talent and some (semi) recent core changes.

**Comment by Belaill** [comment]
The actual problem is with the vmap outdoor/indoor checks i think.

**Comment by HEGladios** [comment]
You are probably right, it's exactly the part that changes were made to.

**Comment by Belaill** [comment]
@HEGladios  This is Thewitcher actualy..but as the name was already taken i will be known as Belaill here

Will look more in to this tomorrow and with some luck find the fix to this,leave it to me.

**Comment by HEGladios** [comment]
https://github.com/OregonCore/OregonCore/issues/1262
I think the author of the commit I referenced will probably work this out, or maybe you can post the solution there ^^

**Comment by HEGladios** [comment]
https://github.com/OregonCore/OregonCore/commit/d82cefa275d3b79d8cb6ac4e1c8585b2996d3fad
Will be fixed in one of the next core updates.
