### ISSUE TITLE
Triage

### ISSUE THREAD

**Issue by Bloobeary** [Helios-Empire/Helios-Tracker#145]
The quest needed to advance your First Aid skill past 225 is bugged. You can't target the Injured, Badly Injured and Critically Injured Soldiers with the Triage Bandage to save them. http://www.wowhead.com/quest=6622/triage

**Comment by dikkedeur** [comment]
totally confirmed, tested it on the dev server, and its broken, you hear them dying but they are already laying down.. and selecting them doesnt do anything.

**Comment by dikkedeur** [comment]
fixed
