### ISSUE TITLE
Ring of Blood

### ISSUE THREAD

**Issue by Classic-WoW** [Helios-Empire/Helios-Tracker#149]
Hello,

we have encountered a problem with the ring of blood quests. Starting with the first one:
http://www.wowhead.com/quest=9962/the-ring-of-blood-brokentoe
Once you kill brokentoe (ID 18398) it will say Brokentoe 1/1, but not that it is defeated. So we couldnt turn the quest in.

Since we could not progress into the other quests, we could not tell if those were bugged too.

Kind regards
vega

**Comment by dikkedeur** [comment]
will look on this one on out dev server, and fix it if needed.

**Comment by dikkedeur** [comment]
![schermafbeelding 2016-02-09 om 10 37 34](https://cloud.githubusercontent.com/assets/11842306/12912484/3410a41a-cf19-11e5-9220-d3343b89097c.png)

i had no problems when i killed him i got the credit..
so i cant reproduce this bug, this was btw tested on the live server!

**Comment by dikkedeur** [comment]
be sure to clear your cache and try again, you never know.

**Comment by Classic-WoW** [comment]
Hm..we did try it in a group with a level 70 player. Will try to redo them today.
