### ISSUE TITLE
ETA on fixing the basic mango pathing?

### ISSUE THREAD

**Issue by iaxx** [Helios-Empire/Helios-Tracker#15]

**Comment by HEGladios** [comment]
Not too long hopefully. It's quite high on the priority list right now.

**Comment by iaxx** [comment]
Why wasn't it fixed before the release? i thought this was a pretty important aspect on the list of things before release. You would've noticed the pathing issues in 5-10 minutes of leveling.

**Comment by HEGladios** [comment]
Oregoncore only recently started using the spline system. Clearly they didn't copy it over very well :D

**Comment by dikkedeur** [comment]
should be fixed, please retest

**Comment by HEGladios** [comment]
All movement related issues should be resolved now.
