### ISSUE TITLE
Quest: Veil Skith: Darkstone of Terokk

### ISSUE THREAD

**Issue by Classic-WoW** [Helios-Empire/Helios-Tracker#151]
Hello,

the Quest http://www.wowhead.com/quest=10839/veil-skith-darkstone-of-terokk is bugged.

The Item Rod of Purification (http://www.wowhead.com/item=31610/rod-of-purification) cannot target the Darkstone, so the quest cannot be cmompleted.

**Comment by dikkedeur** [comment]
fixed in next core update.
