### ISSUE TITLE
Quest: Ring of Blood

### ISSUE THREAD

**Issue by Classic-WoW** [Helios-Empire/Helios-Tracker#155]
Hello,

i figured the problem with the questchain rob (http://db.helios-empire.eu/?quest=9962)

*_If *_you do it solo, it says completed. Once you do it with 2 people, you have to do each boss 2 times. 3 people -> 3 times. 

We had to do several bosses more often yesterday. It is complitable but still bugged.

**Comment by dikkedeur** [comment]
that is an underlaying problem... is it with multiple group quests that this happens?

**Comment by Classic-WoW** [comment]
I am not sure. It probably is the usage of "Hey, Player XYZ started the quest, would you like to start it yourself?". The Problem with testing is that normally each player has to do tons of quest before getting a groupquest. Escort quests might be a good way of testing tho.

**Comment by dikkedeur** [comment]
but you all accept the same quest at once right??
or does 1 take it and shares it? since then it might be that problem.

**Comment by Inyu** [comment]
me (mooni) and pat did it yday the last part only and we only killed it once both of us could turn it in.
Pat had the quest already in his questlog when i accepted it maybe this helps

**Comment by Classic-WoW** [comment]
If you accept such a quest in a group, all members get a popup asking if they would like to take it as well.

IF one has the quest already in the log (one of us had the last quest) it will be probably completed. I think such quests will need a lot of testing to figure it out.

**Comment by dikkedeur** [comment]
what if you all take the quest from the questgiver, then make the group??
it seems a problem with questsharing i think when in group... not sure.
then not the quest is bugged but the group sharing itself, something to look at?

**Comment by Classic-WoW** [comment]
If all take it and then join group - mob will spawn x5. Its probably a bug with the sharing thing, yes.

**Comment by Classic-WoW** [comment]
Acidentally closed it, so reopen xd

**Comment by HEGladios** [comment]
Seems to be working just fine if one player starts the quest and the rest accepts through the automatic quest sharing popup.
