### ISSUE TITLE
Quest: Shattering the Veil

### ISSUE THREAD

**Issue by Classic-WoW** [Helios-Empire/Helios-Tracker#156]
Hello,

http://db.helios-empire.eu/?quest=9849 has the same problem like #152 

You can shatter the same elemental as much as you feel like. Mages can happily bomb through it - thus too easy.

**Comment by dikkedeur** [comment]
fixed in next core update, you can use the item on the shattered rumbler, then it will crush and minions will spawn out of him that you need to kill.
