### ISSUE TITLE
Shaleskin Flayer dont get dmg from magic

### ISSUE THREAD

**Issue by Masterwer** [Helios-Empire/Helios-Tracker#158]
Shaleskin Flayer north from Area 52 in Netherstorm dont take any magic damage

Spell: [http://db.helios-empire.eu/?spell=36576](http://db.helios-empire.eu/?spell=36576)
Npc: [http://db.helios-empire.eu/?npc=20210](http://db.helios-empire.eu/?npc=20210)
Edited by Cela: added npc / spell links

**Comment by Masterwer** [comment]
need to correct me only the ones with the selfbuff shaleskin dont take magic dmg

**Comment by HEguinness** [comment]
Another note to devs:
Not all Shaleskin Flayer mobs have the aura/spell, it appears that some have it and some don't, take it into consideration.

**Comment by HEguinness** [comment]
```
SET @ENTRY := 20210;
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`=@ENTRY;
(@ENTRY,0,0,0,4,0,100,1,0,0,0,0,11,36576,0,0,0,0,0,1,0,0,0,0,0,0,0,"Shaleskin Flayer - On Aggro - Cast 36576");
```

**Comment by HEGladios** [comment]
Fixed after next core update. Thanks @HEguinness.
