### ISSUE TITLE
[Talent] Improved Drain Soul

### ISSUE THREAD

**Issue by DreadfulBioMonster** [Helios-Empire/Helios-Tracker#16]
Tier 2 Affliction talent intended to restore 15% of Maximum Mana upon a target's death while channeling Drain Soul on that target.

It does not.

I have tested it both while dots are on my target, with my pet attacking and not attacking, and with only drain soul dealing any form of damage. None of which trigger the effect.

The only Addon I am currently using is Bagnon.

**Comment by dikkedeur** [comment]
fixed in new core revision
