### ISSUE TITLE
Quest: On Spirit Wings

### ISSUE THREAD

**Issue by Classic-WoW** [Helios-Empire/Helios-Tracker#160]
Hello,

http://db.helios-empire.eu/?quest=10714 does not work proplerly. It does not become completed once you once you use the item to spy on them.

It is required for the main questchain of blade edges mountain with sweeeet rewards.

**Comment by dikkedeur** [comment]
maybe not my finest implementation to fix a quest, but when you get near the 2 ogres and you have quest incomplete and the item it will spawn the raven or spirit, and you get quest credit.

for now this is a work around and will do.

**Comment by dikkedeur** [comment]
ow and active after next core update 👍

**Comment by Flaktrack** [comment]
Somehow this isn't working properly. The raven spirit spawns near the ogres but the quest stays incomplete.

**Comment by HEGladios** [comment]
You are right, the quest still appears as incomplete. However, you can still turn the quest in at the questgiver.

**Comment by Flaktrack** [comment]
Hehe thanks for the clarification .. now i understand ;-) it worked

**Comment by HEGladios** [comment]
I've already made some changes to the script, after the next core update it should properly give quest credit.
