### ISSUE TITLE
"Grandmaster Vorpil" in Shadow Labyrinth 

### ISSUE THREAD

**Issue by Inyu** [Helios-Empire/Helios-Tracker#161]
In this bossfight voidwalker spawn on specific locations and if they reach the boss they detonate and deal aoe dmg and heal the boss.
The problem here is that the voidwalkers are too fast (movementspeed is the same as normal mobs)
here is a vid from 2007 where you can see the voidwalkers are rly slow like it should be
https://www.youtube.com/watch?v=1zn538fRQ98

**Comment by HEGladios** [comment]
Fixed in next core update.
