### ISSUE TITLE
Alchemy Discoveries might not work

### ISSUE THREAD

**Issue by Masterwer** [Helios-Empire/Helios-Tracker#163]
So I tried to get some Flask recipes by making jung elexiers and potions and i can´t get discoveries at all i dont know if i´m unlucky as hell or it doesn´t work at all so pls test it on dev lvl

**Comment by dikkedeur** [comment]
![schermafbeelding 2016-02-13 om 19 57 36](https://cloud.githubusercontent.com/assets/11842306/13029423/4d7b7846-d28c-11e5-8820-bb8ed252f7ee.png)

it does, work..
maybe you are unlucky, and i will show you the following changes.

http://db.helios-empire.eu/?spell=28575 has 30% change on learning http://db.helios-empire.eu/?spell=41458
same as other cauldrons that you can learn, from the appropriate major protection potions out there.

the following have a 0.1% change on learning.. yes they are truly low.. so if that what what you where trying.. then yes it might seem that it doesnt work, but it has just very veyr low change.

http://db.helios-empire.eu/?spell=28582
http://db.helios-empire.eu/?spell=28583
http://db.helios-empire.eu/?spell=28581
http://db.helios-empire.eu/?spell=28582
http://db.helios-empire.eu/?spell=28580
http://db.helios-empire.eu/?spell=28584
http://db.helios-empire.eu/?spell=28585
http://db.helios-empire.eu/?spell=28586
http://db.helios-empire.eu/?spell=28589
http://db.helios-empire.eu/?spell=28591
http://db.helios-empire.eu/?spell=28588
http://db.helios-empire.eu/?spell=28582
http://db.helios-empire.eu/?spell=28587
http://db.helios-empire.eu/?spell=28590
again those have 0.1 %

so for me it seems not bugged :+1:
