### ISSUE TITLE
You, Robot

### ISSUE THREAD

**Issue by ghost** [Helios-Empire/Helios-Tracker#164]
So the issue i found in regards to the bug with this quest is the mob your needed to kill "Negatron" is unattackable, and doesn't move from his spawn point.

**Comment by dikkedeur** [comment]
http://db.helios-empire.eu/?quest=10248

**Comment by dikkedeur** [comment]
fixed in next core update.
Negatron is still not moving from his spawnpoint, you need first to take control over the scrab reaver, and with him you attack negatron, you use him to make the first blow, negatron will then attack you and then you must survive :+1:
