### ISSUE TITLE
Quest "The Ashtongue Corruptors"

### ISSUE THREAD

**Issue by Inyu** [Helios-Empire/Helios-Tracker#166]
2 of the 4 mobs you have to kill are immune to everything.
There are totems besides them which prevent dmg to them but even after killing the totems they are immune.
http://db.helios-empire.eu/?quest=10574 this is the q

the 2 mobs which cant be killed
http://db.helios-empire.eu/?npc=21416
http://db.helios-empire.eu/?npc=21709

**Comment by dikkedeur** [comment]
you should indeed kill first the totems, then when totems are away they should not be immune, thats as far as i know is the way to go.

**Comment by Inyu** [comment]
the water one is still immune even after the totems are dead
and at the earth guy 1 totem is immune too same as the guy itself

**Comment by HEGladios** [comment]
I completely rescripted all totems used by the quest mobs.
Everything is working 100% now.
