### ISSUE TITLE
Rogue pickpocket does nothing

### ISSUE THREAD

**Issue by notaslave** [Helios-Empire/Helios-Tracker#167]
The animation triggers properly and if you fail you then leave stealth and agro the mob as you are supposed to, however pickpocket provided no loot, nor did it even open the loot window. I've only tested it on things around the starting zones but I'll update this if I find it's not working in outlands as well.

**Comment by HEGladios** [comment]
Interesting. I'll have a look.

**Comment by HEGladios** [comment]
Should be fixed on next core update.

**Comment by dikkedeur** [comment]
will update today gladios, so no problem :P

**Comment by notaslave** [comment]
Thanks for looking into it, I've only been here for a few hours but it's nice to see the devs jumping on the issues

**Comment by dikkedeur** [comment]
we do our best notaslave, some bugs might take longer or are simply due scripting not always possible to fix, but when we can we will do it. :+1:

**Comment by notaslave** [comment]
Well I've noticed you don't have any rogues on the server that are 70 yet so I'll go through and see if I find anything else bugged. thanks guys!

**Comment by dikkedeur** [comment]
thanks, if you encounter anything, feel free to make a bug report and we will do our best!

**Comment by notaslave** [comment]
Will do, by the way is there anyone I can talk to in game about some server info and stuff?

**Comment by dikkedeur** [comment]
you can do /join global to interact with other people, it will join the global channel, otherwise contact me on the forum :+1:
