### ISSUE TITLE
Lava in Undercity?

### ISSUE THREAD

**Issue by notaslave** [Helios-Empire/Helios-Tracker#168]
So I went for a swim in UC and died from lava damage, this is my first time seeing something like that, and as long as people avoid the green lava water they'll be fine.

**Comment by notaslave** [comment]
Also upon release it released me directly above my corpse and will not allow me to res.

Correction: it allowed me to res after waiting 30 seconds.

**Comment by dikkedeur** [comment]
interesting.... will take a look on where it is, or do you have an exact location???

http://db.helios-empire.eu/?maps

can you make a link on the spot where it is??
like something like this? > http://db.helios-empire.eu/?maps=1497:500403

**Comment by dikkedeur** [comment]
ugh confirmed, this is a problem propably with vmaps/mmaps.

will take this further.

**Comment by notaslave** [comment]
Sorry to be throwing this list of stuff on you guys, just trying to report what I find.

**Comment by HEGladios** [comment]
Don't worry about it! We greatly appreciate the reports, it helps us fix things faster.

**Comment by MissSnowy** [comment]
I don't think it is a bug in all honesty.

I'm going to have to find the article again, but I do believe at one point it might have been in Vanilla where the slime in UC actually did harm you if you swam in it.

I'll update my posting when I find it again.

**Comment by dikkedeur** [comment]
fixed, also slime in naxx does damage now, and more liquid updates
