### ISSUE TITLE
Rogues Kick only interputs

### ISSUE THREAD

**Issue by notaslave** [Helios-Empire/Helios-Tracker#169]
The Kick spell on a rogue will only interrupt the cast rather than prevent them from casting that school for 5 seconds. So far I've only tested this on npc's. I'll update it if I get to test it on a player as well.

**Comment by HEGladios** [comment]
This is actually a bug with creature AI, the spell school lock-out works on players.
Going to close this issue as the Kick ability works correctly.

**Comment by notaslave** [comment]
Alright, thanks.
