### ISSUE TITLE
Quest: The Weaver

### ISSUE THREAD

**Issue by notaslave** [Helios-Empire/Helios-Tracker#172]
It seems casters do more damage than they should, with that happening, you can't get into the room to kill and loot Archmage Ataeric before they kill you within a matter of seconds. If the spell damage can't be fixed then simply removing the caster adds in the room seems like a viable work-around.Void Walkers do not despawn as they should when the conjurer is killed as well.

**Comment by dikkedeur** [comment]
got this one on my tail

**Comment by dikkedeur** [comment]
void walkers despawn now when you kill the caster...

**Comment by dikkedeur** [comment]
rescripted some of the npcs in that area aswell,
