### ISSUE TITLE
The Gatewatchers in Mechanar

### ISSUE THREAD

**Issue by ghost** [Helios-Empire/Helios-Tracker#174]
Kind of bug: npc/quest/spell/instance/ ( include a link to helios database please for link look below )
NPC http://db.helios-empire.eu/?npc=19710, http://db.helios-empire.eu/?npc=19218
What bug do you encounter?:
The gate watchers respawned after being killed, which when we pulled the first boss almost wiped us.
How to reproduce your bug?:
They kept respawning after being killed, i want to say 10-15 minutes respawn at least once more, van't say if they spawned a third.
How it should work?:
I believe they shouldn't respawn although i guess i could be wrong, been a few years. :0
Operating System:
- Please first search before making a new issue on our tracker.
- Please fill in above template to submit a new issue.
- Use always helios database links > http://db.helios-empire.eu to quests/npcs/spells etc.

**Comment by notaslave** [comment]
Gate watchers should act as a mini boss (of sorts) and should not respawn, that much I know from plenty of experience wiping when it was current.

**Comment by HEGladios** [comment]
Fixed in next core update.
