### ISSUE TITLE
Unable to donate to the server

### ISSUE THREAD

**Issue by Razured** [Helios-Empire/Helios-Tracker#176]
Kind of bug: I'm just unable to place a donation for you guys..  And I don't know why!

What bug do you encounter?: It says "We were unable to authorize your card."

How to reproduce your bug?: -

How it should work?: You having my money! :3

Operating System: - 
- Please first search before making a new issue on our tracker. -
- Please fill in above template to submit a new issue. - 
- Use always helios database links > http://db.helios-empire.eu to quests/npcs/spells etc. -

**Comment by HEguinness** [comment]
Post your issue on our forum, since this isn't about a server bug.
http://forum.helios-empire.eu/viewforum.php?f=12&sid=ef0a9e9d88364268206c39829e41749a
Make a topic there, and describe everything, im sure the santa will answer shortly after.

**Comment by dikkedeur** [comment]
you may also pm me on the forum Razured since it might contain personal information.

gr.
Dikkedeur
