### ISSUE TITLE
RaF xp incorrect?

### ISSUE THREAD

**Issue by notaslave** [Helios-Empire/Helios-Tracker#177]
It seems like the xp from RaF is set to 5x the normal rate which is 3x so you end up receiving 15x xp on anything you do, I may be wrong on this but if the quest [http://db.helios-empire.eu/?quest=2875](http://db.helios-empire.eu/?quest=2875) is supposed to reward 5.5k, at 3x you will receive 16.5k, however when turned in we received something close to 100k xp.

not sure if this was intentional or not but a level from every quest is really extreme.

**Comment by notaslave** [comment]
1.67x the normal rates (3x) should add up correctly with juuuust slightly over the 5x you want.

**Comment by HEGladios** [comment]
Should be fixed now. I think pets will get a little bit more XP as well now.
