### ISSUE TITLE
NPC missing

### ISSUE THREAD

**Issue by androgin** [Helios-Empire/Helios-Tracker#18]
For the paladin quest Tome of Divinity cannot seem to find the John turner NPC in his spots in Ironforge.

**Comment by dikkedeur** [comment]
went there, he is not on the spawn location but that is because he is walking around, havent find him since, seems that he lost also lost.
so for now i have spawned him until i find a better solution.

**Comment by androgin** [comment]
Found the NPC, and i continued the chain of quest to the end. At the last part of the Tome of divinity quest when i was about to speak with the Muiredon Battleforge NPC to receive the ressurection spell it broke again. The quest completed but i did not received the ressurection spell in my spell book. thx.

**Comment by androgin** [comment]
solved, it appeared!
