### ISSUE TITLE
Fishing Bobber Not going away

### ISSUE THREAD

**Issue by MissSnowy** [Helios-Empire/Helios-Tracker#180]
Kind of bug: npc/quest/spell/instance/ ( include a link to helios database please for link look below )
http://db.hellground.net/?item=6256

What bug do you encounter?:
When fishing, the bobber icon takes a long time to vanish, leaving the fishing area filled with bobber icons'

How to reproduce your bug?:
Just go fishing and wait to catch or miss a fish.

How it should work?:
The bobber icon should vanish after each attempt at fishing.

Operating System: Windows 10

Screen Shot
![bobber](https://cloud.githubusercontent.com/assets/15068526/13249721/e55e1c9a-d9f3-11e5-8736-d8fa632b2dcb.png)

**Comment by dikkedeur** [comment]
yeah when you move it gets away is visual bug, i have that when i spawn a npc and delete it, it stays there till i move my butt :+1:

**Comment by Inyu** [comment]
i encountered it too it wasnt a big issue since you just have to move the camera a bit and they despawn

**Comment by dikkedeur** [comment]
its also with npc's when you delete them, you will not notice it, but me as admin does :P

**Comment by Bloobeary** [comment]
It happens with hunter pets as well - when you stable them or dismiss them.

**Comment by dikkedeur** [comment]
lol, as mentioned it is with everything in the world that needs to be removed, when you move you dont see it, it looks like there is a tick missing when you call it, and it only gets called when a update movement package is sent..

**Comment by Flaktrack** [comment]
Pretty annoying issue because it affects the shaman totems too.
When a totem gets "killed" and you don't move, it stays in the world and remains targetable although it isn't really there anymore ...

**Comment by dikkedeur** [comment]
Fixed
