### ISSUE TITLE
Shaleskin Flayer

### ISSUE THREAD

**Issue by Razured** [Helios-Empire/Helios-Tracker#186]
Kind of bug: It's a NPC, the name is Shaleskin Flayer in Netherstorm and the Shaleskin are a part of the early questing chains in the zone.

What bug do you encounter?: I can't do any damage to the NPC, I'm an Elemental shaman and he seem to get hit by my spells but does not receive any damage.

How to reproduce your bug?: I simply attack him

How it should work?: The npc has a spell on him that is named "Shaleskin" and it reduces the effects of magic received by 50% so my spells should do half the damage, but he doesn't receive any damage so it's like a 100% shield

Operating System:
- Please first search before making a new issue on our tracker.
- Please fill in above template to submit a new issue.

Helios Database link: http://db.helios-empire.eu/?npc=20210

**Comment by HEguinness** [comment]
Already reported at the following link:
https://github.com/Helios-Empire/Helios-Tracker/issues/158
