### ISSUE TITLE
Quest: Who are they?

### ISSUE THREAD

**Issue by Bloobeary** [Helios-Empire/Helios-Tracker#188]
Kind of bug:
Quest "Who are they?": http://db.helios-empire.eu/?quest=10041

What bug do you encounter?:
The Questgiver is supposed to give you a buff that disguises you, so you can enter the camp and talk with the quest targets. That doesn't happen - no buff is cast.

How to reproduce your bug?:
Take the quest.

How it should work?:
You should receive a buff that disguises you.

Operating System:
Windows 10

**Comment by HEGladios** [comment]
Duplicate: https://github.com/Helios-Empire/Helios-Tracker/issues/92
