### ISSUE TITLE
Rat's Not Adding Up

### ISSUE THREAD

**Issue by MissSnowy** [Helios-Empire/Helios-Tracker#189]
Kind of bug: npc/quest/spell/instance/ ( include a link to helios database please for link look below )
Quest: http://db.helios-empire.eu/?quest=6661
Item: http://db.helios-empire.eu/?item=17117

What bug do you encounter?: You can charm the rats, it just doesn't count them for the quest requirement.

How to reproduce your bug?: Charm the rats

How it should work?: Each rat charmed should add to the total needed to complete the quest

Operating System: Windows 10

**Comment by dikkedeur** [comment]
when the rat is charmed use the flute again when you are near the questgiver, it will then count, its kinda bugged but still works in some way.
