### ISSUE TITLE
[Quest] The Stones of Vekh'nir

### ISSUE THREAD

**Issue by Storm15** [Helios-Empire/Helios-Tracker#191]
Kind of bug:
Quest The Stones of Vekh'nir http://db.helios-empire.eu/?quest=10565

What bug do you encounter?:
Mobs don't drop Vekh'nir Crystal http://db.helios-empire.eu/?item=30561

How to reproduce your bug?:
Take the quest, kill the mobs in Veil Vekh and they don't drop the crystal.

How it should work?:
It should be 33% chance to drop the crystal if you are on the quest.

**Comment by HEGladios** [comment]
Fixed on next core update.
