### ISSUE TITLE
Infernal Core Quest

### ISSUE THREAD

**Issue by ghost** [Helios-Empire/Helios-Tracker#192]
Kind of bug: npc/quest/spell/instance/ ( include a link to helios database please for link look below )
npc/spell/quest item
http://db.helios-empire.eu/?quest=7603
What bug do you encounter?:
When using the item fel fire for the quest: "Kroshius' Infernal Core" on the remains i receive the error "Requires Kroshius Remains." Either the neutral npc that is currently up is incorrect for the quest summon or i'm not standing in the correct spot.
How to reproduce your bug?:
I believe just accepting the quest and trying to use the item on the dead corpse of Kroshius.
How it should work?:
Based on the information i've found, after using the item, the infernal stands up and is attackable.
Operating System:
- Please first search before making a new issue on our tracker.
- Please fill in above template to submit a new issue.
- Use always helios database links > http://db.helios-empire.eu to quests/npcs/spells etc.

**Comment by dikkedeur** [comment]
you are correct, the object itself is not even spawned, so that is first part of the bug, after spawning you can indeed start the script but after that it does nothing, so i will take a further look at that part aswel.

**Comment by dikkedeur** [comment]
well the object WAS spawned but not on the remains but on the location where he spawns when the script is activated, so moved it to the correct location..
now the npc itself is neutral, so you cant kill it, i will take a further look later on on this one..
added to my to do list.

**Comment by dikkedeur** [comment]
redone the whole bunch, scripted also Kroshius, added also text to him when he spawns..

ENJOY
