### ISSUE TITLE
Quest: What came first, the drake or the egg

### ISSUE THREAD

**Issue by NickEast** [Helios-Empire/Helios-Tracker#194]
Kind of bug: http://db.helios-empire.eu/?quest=10609 http://db.helios-empire.eu/?object=184867
What bug do you encounter?:The second listed item is not spawning the npcs, listed n the first link.

How to reproduce your bug?: Use the second link item

How it should work?:Should spawn npcs, listed in first link

Operating System:Windows 7 x64

**Comment by dikkedeur** [comment]
fixes this in next core update.
you must open the egg, then a whelp will spawn, use the provided item to change the whelp to one of the 3 drakes.. its random as on blizz, then kill the drake and loot him

**Comment by dikkedeur** [comment]
also removed the 4 spawned nether whelp, since they MUST be spawned by the script itself and not being on the map at all unless you have the quest and open the egg.
