### ISSUE TITLE
Nothin' Says Lovin' Like a Big Stinger

### ISSUE THREAD

**Issue by notaslave** [Helios-Empire/Helios-Tracker#195]
Quest bug

While on the quest [http://db.helios-empire.eu/?quest=9898](url) after killing [http://db.helios-empire.eu/?npc=18283](url) he should drop the item [http://db.helios-empire.eu/?item=25448](url) , but upon killing him he dropped nothing.

Pretty sure it should be 100% chance while you have the quest.

Windows 7

**Comment by dikkedeur** [comment]
drop change is 83% as on our database...
on wowhead its 95%

**Comment by HEGladios** [comment]
Your links are broken, please fix them. Also, the drop chance should be 100%.

**Comment by notaslave** [comment]
Tried fixing the links, didn't work, not sure what's wrong with them

**Comment by HEGladios** [comment]
Fixed on next core update.
