### ISSUE TITLE
Missing Friends

### ISSUE THREAD

**Issue by notaslave** [Helios-Empire/Helios-Tracker#196]
When on the quest [http://db.helios-empire.eu/?quest=10852](url) there are cages with multiple children in them, rather then counting the 1-5 children per cage it will only release 1 child at a time.

The children also take well over an hour to start respawning as well.

Windows 7

**Comment by notaslave** [comment]
I apologize the link is broken, I'm not sure why they aren't working

**Comment by HEGladios** [comment]
Looks like your link is formatted like this:
`[http://db.helios-empire.eu/?quest=10852](url)`

All you have to do is literally copy/paste the direct url. So just:
`http://db.helios-empire.eu/?quest=10852`

**Comment by HEGladios** [comment]
Duplicate: https://github.com/Helios-Empire/Helios-Tracker/issues/88
