### ISSUE TITLE
Shield Bash

### ISSUE THREAD

**Issue by kubicka** [Helios-Empire/Helios-Tracker#20]
Shield bash should prevent casting of magic school which was interupted, but its not working.

**Comment by dikkedeur** [comment]
i didnt test it but somebody else did, and he wrote:

Which spells and ranks were you testing this with?
I was not able to reproduce that with Rank 4 Shield Bash on a either a Paladin target casting Holy Light or a Mage target casting Blizzard (to confirm that only Frost would be locked out).

**Comment by dikkedeur** [comment]
not able to reproduce, others also not, so moved to closed

**Comment by HEGladios** [comment]
Side note: This is most likely to do with creature AI. Some creatures seem to be able to ignore spell school lockouts.

**Comment by YujiTFD** [comment]
Sorry for bringing this up, but shieldbashing (http://db.helios-empire.eu/?spell=72) a Murloc Oracle (http://db.helios-empire.eu/?npc=517 casting Holy Smite (http://db.helios-empire.eu/?spell=9734) does NOT prevent it to cast another Holy Smite right away. Same goes for alot of NPCs.

**Comment by Flaktrack** [comment]
Same with **Earth Shock** http://db.helios-empire.eu/?spell=25454
It interrupts the cast but doesn't lock out the appropriate magic school.
In fact a lot of different mobs are able to cast the same previously interrupted spell immediately again.

I could imagine same behavior can be observed with other interrupt spells like Counterspell, Kick or Pummel.

**Comment by dikkedeur** [comment]
As @HEGladios  is mentioning, this could be due creature ai, since the creature you mention is scripted in eventai and we also have Smartai, i will try to convert it then test if this is still the case.
