### ISSUE TITLE
Seal of Righteousness / Vengeance

### ISSUE THREAD

**Issue by saltymofo** [Helios-Empire/Helios-Tracker#202]
Kind of bug: npc/quest/spell/instance
++Seal of Righteousness++ http://db.helios-empire.eu/?spell=20154
++Seal of Vengeance++ http://db.helios-empire.eu/?spell=31801

What bug do you encounter?:
The seal isn't adding holy damage to successful melee attacks and Seal of Vengeance isn't accumulating stacks at all, furthermore, when you judge SoV it heals the mob

How to reproduce your bug?:
Attack any mob with SoR or SoV

How it should work?:
Seal of Righteousness (SoR) should add holy damage to each melee attack
Seal of Vengeance (SoV) should accumulate a stacking damage bonus with successful melee attacks, stacking up to 5 times.

Operating System:
windows 8.1

**Comment by dikkedeur** [comment]
should work now, please retest

**Comment by saltymofo** [comment]
I tried both seals against the mobs I initially had a problem with,
ethereal plunderer and ethereal nethermancer.   Seal of righteousness and
vengeance work fine on the nethermancer. However against the plunderers the
seals do nothing. Perhaps they have a magic immunity?

**Comment by dikkedeur** [comment]
can be, but since it works on other mobs i think its just that and that it works, so mark this as fixed
