### ISSUE TITLE
Dungeon "Black Morast" and Quest "The Master's Touch"

### ISSUE THREAD

**Issue by Inyu** [Helios-Empire/Helios-Tracker#208]
Kind of bug: npc/quest/spell/instance/ ( include a link to helios database please for link look below )
http://db.helios-empire.eu/?quest=10737
http://db.helios-empire.eu/?npc=17881
What bug do you encounter?:
the quest posted above cant be completed and the scripts starts again but since the last wave was 18/18 its starts from 19/18
the last boss drops only 1 item
How to reproduce your bug?:
finish the waves/kill the boss
How it should work?:
after 18/18 medievh should say some stuff and orcs should come out of the portal which completes the whole instance
the last boss should drop 2 items
Operating System:
windows 10
- Please first search before making a new issue on our tracker.
- Please fill in above template to submit a new issue.
- Use always helios database links > http://db.helios-empire.eu to quests/npcs/spells etc.

**Comment by HEGladios** [comment]
Made some changes, hopefully it will be fixed after next core update.
