### ISSUE TITLE
Fleeing mobs teleporting to their destination when CCed

### ISSUE THREAD

**Issue by Seydas** [Helios-Empire/Helios-Tracker#21]
Fleeing mobs teleport to their destination (usually another mob of the same type) when CCed before or after they start fleeing. Tested with gouge and frost nova.

**Comment by dikkedeur** [comment]
does it look like https://github.com/Helios-Empire/Helios-Tracker/issues/14 ?

**Comment by Seydas** [comment]
Yes, it does, the only difference is they teleport when they start fleeing, regardless if they're CCed or not.
Sometimes it happens, sometimes it doesn't, but it's not hard to reproduce.
Oh and also when mobs start fleeing they do not interrupt their casting

**Comment by dikkedeur** [comment]
can you please do step for step guide on how to reproduce, since then we can take a look on how to fix it or OC...
so also what spells do you use to do it, a vid is even better.

**Comment by ghost** [comment]
Can confirm this. When my mate frostnovas a mob and we damage it until it would usually flee, but it can't flee because it's still in frostnova, the mob just teleports somewhere else and runs to you after being released from frostnova.

**Comment by HEGladios** [comment]
This is all related to some movement generator issues. We hope to have them resolved soon!

**Comment by dikkedeur** [comment]
FIXED
