### ISSUE TITLE
Goblin/Gnomish engineering quest.

### ISSUE THREAD

**Issue by Magarus** [Helios-Empire/Helios-Tracker#210]
Kind of bug: npc/quest/spell/instance/ ( include a link to helios database please for link look below )
http://db.helios-empire.eu/?quest=3638
And also
http://db.helios-empire.eu/?quest=3642
What bug do you encounter?:
Quests are missing. You can't take any quest but you can learn all parts from them.
Even if you learn them , you can't use them because you don't have the specialization.
How to reproduce your bug?:
level engineering and go talk with them. No quest will be given but you can learn anything
How it should work?:
You should have http://db.helios-empire.eu/?quest=3642/http://db.helios-empire.eu/?quest=3638 as the first quest + the rest of the chain.
Operating System:

Windows 8,1

**Comment by HEGladios** [comment]
Looks like you should first get one of the quests from this guy. Have you tried this?
http://db.helios-empire.eu/?npc=4586

**Comment by Magarus** [comment]
Dayum!
You are right! <3 You saved my life :o
