### ISSUE TITLE
[spell] Stealth /Prowl

### ISSUE THREAD

**Issue by R3mz** [Helios-Empire/Helios-Tracker#22]
It Seems like Npcs (even grey ones) can see me while I'm prowling/stealthed if I'm walking in front of them. maybe it's 'work as intended' but npcs with 6 level below me shouldn't be able to see me like if I was unstealthed. 
 edit : After testing I can't even stay stealthed more than 1 second BEHIND them.

![wowscrnshot_081515_155816](https://cloud.githubusercontent.com/assets/13809952/9289148/e78997b6-4366-11e5-9640-1b1cb9928025.jpg)

**Comment by dikkedeur** [comment]
tested this on dev server, was not able to reproduce it.. there where cases where i agro the ncp but that was when totally running through the npc stealthed.

**Comment by HEguinness** [comment]
Strange, i could reproduce this few days ago... anyway it works now so wohoo.

**Comment by dikkedeur** [comment]
i can only reproduce this when you go straight trough the mob, duh i would feel some shady ass motherfucker then aswell :p moeha, 
but not when you are a few yards behind the mob.

tested with 6 levels difference mob, as report is saying
