### ISSUE TITLE
Hellfire Ramparts

### ISSUE THREAD

**Issue by dannzor00** [Helios-Empire/Helios-Tracker#223]
Kind of bug: npc/quest/spell/instance/ ( include a link to helios database please for link look below )

What bug do you encounter?: Bosses do extremly high damage and spams spells, same with regular mobs, and the loot just dissapears

How to reproduce your bug?: 

How it should work?:

Operating System:
- Please first search before making a new issue on our tracker.
- Please fill in above template to submit a new issue.
- Use always helios database links > http://db.helios-empire.eu to quests/npcs/spells etc.

**Comment by dikkedeur** [comment]
Hellfire ramparts have been modified a few months ago because it was doing almost NO damage.
it can be that we took things a bit too serious.
we took in this case the values from mangos database ( is not what we use ) so it might be that we are kinda off with the damage.
Spam spells, is that on bosses and can you tell me more about it? or is it the trash??

**Comment by dannzor00** [comment]
It's both the thrash and bosses, the dragon (dont remember name) Shoots his Conflag like a machine gun, there is fire all over the place.  The conlfag does 6k damage lol. The ranged thrash uses their abilites all the time. No internal CD. sry for my bad english

**Comment by dannzor00** [comment]
Yeah and the hound master calls his dog like 10 sec late, and he summons like 10 of em, when it is suppose to be 2-3

**Comment by dikkedeur** [comment]
thanks for the heads up, something to look into i see ^^

**Comment by dannzor00** [comment]
one more thing i forgot to mention. the Mobs sometimes bugs throu the ground aswell. Thank you for ur time.

**Comment by dikkedeur** [comment]
fixed in next core update.

a total revamp of the whole instance has been done, all spawns redone and formations, also all trash has better spell handling and text now.
