### ISSUE TITLE
A Spirit Guide (Mag'har attunement quest)

### ISSUE THREAD

**Issue by Cio0** [Helios-Empire/Helios-Tracker#225]
Kind of bug: npc/quest/spell/instance/ ( include a link to helios database please for link look below )
I cannot complete http://db.helios-empire.eu/?quest=9410

What bug do you encounter?:
The escort mob (http://db.helios-empire.eu/?npc=17077) gets hit and you lose the buff needed to interact with the turn in NPC (http://db.helios-empire.eu/?npc=16845). See SS of combat log: http://i.imgur.com/bYh3iK3.jpg

How to reproduce your bug?:
Do the quest by following the spirit wolf, make sure not to kill the hellboar around the corner.

How it should work?:
NPC should temporarily become interactable for characters who followed the wolf (flagged as horde generic) instead of Mag'har until completion of the chain. See the top wowhead comment from 2.4.3: http://www.wowhead.com/quest=9410/a-spirit-guide

Operating System:
W7

Suggested fix:
set http://db.helios-empire.eu/?npc=16845 to horde generic, non-pvp flagged. Quest chain limits you enough nobody should be able to tell the difference.

**Comment by dikkedeur** [comment]
i was not able as you know to get the same result, it was propably a bug on your char that you had this problem, and has been solved.
i tried it on my test server with another char, and was not able to get the same result.

lets keep it that you where unlucky and gm help was needed in this way ^^
