### ISSUE TITLE
Negative health on reaching level 15 as BE paladin

### ISSUE THREAD

**Issue by Cio0** [Helios-Empire/Helios-Tracker#227]
Kind of bug: Game mechanics

What bug do you encounter?:
When dinging 15 on a BE paladin, my health is reduced by 1. See https://i.imgur.com/yl0umik.jpg

How to reproduce your bug?:
Grab a BE Paladin and level it!

How it should work?:
No clue on exact numbers, but -1 can't possibly be right.

Operating System:
W7

**Comment by dikkedeur** [comment]
confirmed, i dont even need to make a char, i went into the database and found it, funny thing.. even on tc it is still broken, i heard about it before.
now i need to fid the correct data.. but i will work on it.
the nice part is that when you levelup 1 level it gets corrected, but it looks sloppy

**Comment by dikkedeur** [comment]
fixed in next core update, thanks for the report.
