### ISSUE TITLE
[Quest] [Dustwallow Marsh] The Grimtotem Weapon not working

### ISSUE THREAD

**Issue by Flaktrack** [Helios-Empire/Helios-Tracker#229]
The Quest The Grimtotem Weapon does not work. If you drop the totem next to a crocolisc and kill it, nothing happens.

Steps to reproduce
1. Obtain Quest The Grimtotem Weapon
2. Drop totem
3. Pull crocolisc into the totem
4. Kill it, no credit gained.

Database Link
http://db.helios-empire.eu/?quest=11169

Video - how it should work:
https://www.youtube.com/watch?v=5KYh9AGO_wQ

**Comment by dikkedeur** [comment]
strange, on the testserver it does work

![schermafbeelding 2016-04-13 om 10 46 57](https://cloud.githubusercontent.com/assets/11842306/14487834/21ba588c-0165-11e6-8a05-aa25825484e7.png)

**Comment by dikkedeur** [comment]
i see, it only works on 1 mob and not on the other..

**Comment by dikkedeur** [comment]
i will assign same script to that other croc, so that it works, i have already tested that..
will be active on next core update.
