### ISSUE TITLE
[Talents][Hunter] Improved Mend Pet

### ISSUE THREAD

**Issue by Flaktrack** [Helios-Empire/Helios-Tracker#230]
Improved Mend Pet is supposed to add a 25/50% chance to dispel negative effects **each tick** of Mend Pet, currently it only has a chance on the **initial cast**.

Rank 1 - http://db.helios-empire.eu/?spell=19572
Rank 2 - http://db.helios-empire.eu/?spell=19573

**Comment by dikkedeur** [comment]
Will be fixed in next core update.
