### ISSUE TITLE
[Paladin] auras, SoC, blessings are broken in groups!

### ISSUE THREAD

**Issue by Cio0** [Helios-Empire/Helios-Tracker#231]
Kind of bug: spell

What bug do you encounter?:
Refreshing auras dispel other paladin's buff's like (G)BoM/(G)BoW, and also seals! SoC also dispels other paladins auras/blessings.

How to reproduce your bug?:
Take two paladins. Stick em in a group. Buffs will disappear left and right and you enter/exit each other's aura range. Example of SoC dispelling aura http://imgur.com/a/GkUzS (top: PalyMD has devo aura on, it's applied to me. bottom: I cast SoC, removing the devo aura from me)

How it should work?:
Seals, judgements, and blessings should be 'per paladin'. Aura's should only dispel the same aura of a lower rank. Blessings of the same type cannot stack (Gbom + bom for example).

It's like buff slots are all wonky. I suspect SoC also dispels blessings and shouts from other players, but testing was a mess.

**Comment by dikkedeur** [comment]
fixed
