### ISSUE TITLE
[Database] Non-existant herb respawn timer in Outland?

### ISSUE THREAD

**Issue by Flaktrack** [Helios-Empire/Helios-Tracker#236]
I think there is something wrong with the respawn timer of herbs, from what i've seen, in Helfire Peninsula and Zangarmarsh - maybe in more zones. There are almost no herb nodes.
Felweed http://db.helios-empire.eu/?item=22785
Dreaming Glory http://db.helios-empire.eu/?item=22786
and some more.
Sure it's possible that someone gathered all, but perhaps you can take a look.

**Comment by dikkedeur** [comment]
http://db.helios-empire.eu/?object=181270

better look for the object, those contains the actual items.
then again you see there are roughly 100 objects of them, but they spawn in a pool so when 1 is taken then it hops/spawns another one in a pool
so there are not 100 spawns in general at the same time.

**Comment by dikkedeur** [comment]
bij looking in the database, there should be 30 herbs spawned in shadowmoon valley at once, that is felweed.. its possible to alter all those pools, but takes some time.
so its not that there is nothing to be found.

**Comment by dikkedeur** [comment]
https://github.com/Helios-Empire/Helios-Tracker/issues/25
