### ISSUE TITLE
Quest: Vile Familiars in Durotar

### ISSUE THREAD

**Issue by ghostlynx-helios** [Helios-Empire/Helios-Tracker#239]
Kind of bug: quest

What bug do you encounter?: Is unavailable to my blood elf hunter

How to reproduce your bug?: Checked quest with level 2 orc warrior and is available.  Quest has no prerequisites and should be offered to any race/class except warlocks. Also, the quest calls to kill 12... the original quest should be 8.  Warlocks recieve a different version that eventually gets them their imp pet. 

How it should work?: http://wow.gamepedia.com/Quest:Vile_Familiars.  This is the first quest in a chain.

Operating System: Windows 10
- Please first search before making a new issue on our tracker.
- Please fill in above template to submit a new issue.
- Use always helios database links > http://db.helios-empire.eu to quests/npcs/spells etc.

**Comment by Flaktrack** [comment]
Additional Info:
Helios DB - [4] Vile Familiars http://db.helios-empire.eu/?quest=792
Thottbot 2007 (12 kills) http://web.archive.org/web/20071215094114/http://thottbot.com/q792

**Comment by dikkedeur** [comment]
wonder why thottbot says 12 and wowhead 8 ??
do we have data to back up it must be 8 and not 12?

**Comment by Flaktrack** [comment]
As the historical thottbot und the old comments on wowhead indicate 12 kills, I assume that they changed the quest during the zone-revamp of the cata patch 4.0.3

new quest added in patch 4.0.3 - http://www.wowhead.com/quest=25131/vile-familiars

So i think 12 kills is the way to go for TBC :-)

**Comment by dikkedeur** [comment]
fixed in next core update.
