### ISSUE TITLE
Soul Siphon

### ISSUE THREAD

**Issue by Sleekcrush** [Helios-Empire/Helios-Tracker#24]
Does not increase the percentages by an additional 2% for each affliction spell on the target. The amount healed stays the same even if there is no affliction spells on the target.

**Comment by ghost** [comment]
Unless this was changed, i have noticed that the spell drain life does increase when the talent soul siphon is picked up, can not say if it's 2% but it does increase, with each affliction spell on the target.

**Comment by dikkedeur** [comment]
So can we say this one works now, there was some code added that did something to healing by spells..
so please can you totally confirm this is working as intended now?
