### ISSUE TITLE
Powering Our Defenses quests (Eversong Woods)

### ISSUE THREAD

**Issue by ghostlynx-helios** [Helios-Empire/Helios-Tracker#241]
Kind of bug: Quest (http://db.helios-empire.eu/?quest=8490)

What bug do you encounter?: Recieved message 'Objective Complete' but does not show completed in quest log and cannot turn in.

How to reproduce your bug?: Tried placing the rune stone again, this time, no waves happen, nothing.  Just the infused crystal sitting there.  Note that when I first arrived at the stone, two infused crystals were already in place, I placed mine and then fought off the (triple) waves that followed.

How it should work?: Once placing the crystal, you should fight off several waves for a minute, then the rune is energized and quest completes.

Operating System: Windows 10
- Please first search before making a new issue on our tracker.
- Please fill in above template to submit a new issue.
- Use always helios database links > http://db.helios-empire.eu to quests/npcs/spells etc.

**Comment by dikkedeur** [comment]
confirmed, im on something, dont know if it will fix it.. if so i will let you know.

**Comment by dikkedeur** [comment]
got it... reworking on everything and fixed it.. it looks way better now.. also quests credit works.
will be active in next core update.

thanks for the report.
