### ISSUE TITLE
Little dash of seasoning, Attack on Zeb'Tela, Assault on Zeb'Nowa, Shadowpine Weaponry

### ISSUE THREAD

**Issue by ciyle** [Helios-Empire/Helios-Tracker#242]
Kind of bug: npc/quest/spell/instance/ ( include a link to helios database please for link look below )
http://db.helios-empire.eu/?quest=9275
http://db.helios-empire.eu/?quest=9276
http://db.helios-empire.eu/?quest=9277
http://db.helios-empire.eu/?quest=9214

Bug relates to the quests resetting on server restart and when I log on

What bug do you encounter?:

I had logged out this morning with miminal progress made on these quests. On logging in again this afternoon the server crashed times. Both times I lost all further progress made on these quests (including completing them, and levelling to 20).

How to reproduce your bug?:

Getting disconnect or losing all progress when the server restarts. This might be due to maintenance and server shut downs, it might be a bug. I don't really want to complete the quests again for a fourth time.

How it should work?:

The quests I assume would stay completed, and I would stay levelled :)

Operating System:

Windows 10
- Please first search before making a new issue on our tracker.
- Please fill in above template to submit a new issue.
- Use always helios database links > http://db.helios-empire.eu to quests/npcs/spells etc.

**Comment by dikkedeur** [comment]
it might be due latest core changes, we are reverting... and see if this fixes the above, the server itself was not dc'ing but reloading chars where or saving..

**Comment by dikkedeur** [comment]
can you confirm if everything is back to normal right now?

**Comment by ciyle** [comment]
Re-doing the quests now.

So far it looks like that worked, thanks very much for the help and sorry in the delay in responding.

**Comment by ghostlynx-helios** [comment]
I just did the quests in this area and worked, there was a few minutes lost DC when I first started killing the ones around Zeb'Nowa, but it was an apparently unrelated issue.  There are two minor issues that I will address here:

Headhunters - some of them will not move when attacked until they reach their 'run' hp threshold.  Which means they can be safely ranged attacked without consequences.  Not all of them exhibited this bug.

Catlords - they should have a summoned ghostclaw lynx companion, that will desummon when the catlord is killed and will attack you while he is alive.  None of them had any lynx companions.

**Comment by ciyle** [comment]
Now you mention it, I remember vaguely that Catlords had pets (forgive me, it's been years since I last played the game). And I agree - the Headhunters didn't move a lot. As I'm levelling a priest I didn't really notice.

Completely unrelated and my apologies to that, but the herb spawns seem extremely low as well. I gather this is to prevent botting, but thus far I've been unable to get herbalism past 30 and I'm one of those who picks everything they see.

(oh and yes, agree with ghostlynx - this fixed the problem but the mobs AI is a little off. Still - thanks for all your hard work. It's a great server and levelling experience so far).

**Comment by dikkedeur** [comment]
do you guys have ID's of those creatures, so i can take a better look on them??

**Comment by ciyle** [comment]
I believe the creature IDs are as follows;

Shadowpine Catlord - 16345
Shadowpine Headhunter - 16344

The other types of enemy related to these quests (in case this is useful to you);

Shadowpine Hexxer - 16346
Shadowpine Shadowcaster - 16469
Kelgash the Wicked - 16358

**Comment by dikkedeur** [comment]
catlords are fixed in next core update, i also took a look at the script headhunters, but it seems that the disable combat movement is just part of it.. i need to take a look into that, but it seems they took values form blizz.
