### ISSUE TITLE
Lament of the Highborne

### ISSUE THREAD

**Issue by ghostlynx-helios** [Helios-Empire/Helios-Tracker#243]
Kind of bug: Journey to Undercity quest. http://db.helios-empire.eu/?quest=9180

What bug do you encounter?: Visible 'spell bunnies' for the lightning discharge effects that happen while Sylvanas sings the lament.  They appear to be large imps and are named 'Lament of the Highborne spell bunnies' They cast the spell effect at each other.

How to reproduce your bug?: n/a

How it should work?: The 'spell bunnies' should not be visible. If this is a hard fix, just eliminate them completely along with the spell special effects and this will be a good enough fix.

Operating System: Windows 10
- Please first search before making a new issue on our tracker.
- Please fill in above template to submit a new issue.
- Use always helios database links > http://db.helios-empire.eu to quests/npcs/spells etc.

**Comment by dikkedeur** [comment]
fixed in next core update, making the bunnies invisible...
