### ISSUE TITLE
Broken Quest: Alliance , Shatter Point

### ISSUE THREAD

**Issue by deeaz** [Helios-Empire/Helios-Tracker#246]
Kind of bug: http://db.helios-empire.eu/?quest=10340

What bug do you encounter?:  Wing Commander Dabir'ee does not send you to Shatter Point , only sends you on a flight path loop back to him

How to reproduce your bug?:  Talk to Wing Commander Dabir'ee 

How it should work?:  Wing Commander Dabir'ee should send you to Shatter Point

Operating System: 8.1

**Comment by deeaz** [comment]
also seems to be missing the quest before http://db.helios-empire.eu/?quest=10146

**Comment by dikkedeur** [comment]
both issues fixed in next core update.
