### ISSUE TITLE
[Quest][Blade's Edge Mountains] Gather the Orbs

### ISSUE THREAD

**Issue by Flaktrack** [Helios-Empire/Helios-Tracker#247]
[67] Gather the Orbs http://db.helios-empire.eu/?quest=10859

The provided "Orb Collecting Totem" http://db.helios-empire.eu/?item=31668 should attract the purple  floating orbs. Currently the orbs are correctly heading towards the totem but they destroy it immediately and give no quest credit.

**Comment by HEGladios** [comment]
Confirmed.

**Comment by dikkedeur** [comment]
Fixed on next core update.
