### ISSUE TITLE
[Quest][Blade's Edge Mountains] Death's Door

### ISSUE THREAD

**Issue by Flaktrack** [Helios-Empire/Helios-Tracker#249]
[68] Death's Door http://db.helios-empire.eu/?quest=10910

Used in the subzone Death's Door, the provided "Druid Signal" http://db.helios-empire.eu/?item=31763 should call an "Evergrove Druid" http://db.helios-empire.eu/?npc=22423
There are a lot of "flying question marks" but no druid descends, lands and ends/starts the quests.

**Comment by dikkedeur** [comment]
fixed in next core update... when spell hits druid in the sky he will fly down.

**Comment by deeaz** [comment]
Dont know if its been implemented yet , but evergrove druids (  http://db.helios-empire.eu/?npc=22423 )  come down when using the flare , but dont stay. once they get to ground level the instantly fly back up to the sky making it next to impossible to interact with
