### ISSUE TITLE
[Alliance Quest] Trial of the Sea Lion

### ISSUE THREAD

**Issue by yashirotcm** [Helios-Empire/Helios-Tracker#250]
Kind of bug: npc/quest/spell/instance/: http://db.helios-empire.eu/?quest=272

What bug do you encounter?: The half pendant of Aquatic Endurance is NOT spawned in the world, therefore, aquatic form for druids cannot be acquired as this quest chain is necessary.

How to reproduce your bug?: Go to Westfall (coords (17,32)) and it will not be there.

Operating System: Windows 7 64-bit.

**Comment by dikkedeur** [comment]
the both pendants are there, you can look that up here >
http://db.helios-empire.eu/?item=15882
you see there are 2 on 2 different locations

**Comment by dikkedeur** [comment]
![schermafbeelding 2016-05-08 om 00 21 35](https://cloud.githubusercontent.com/assets/11842306/15094907/e2e6ef9c-14b2-11e6-8231-90e6ad6ba7a2.png)

**Comment by dikkedeur** [comment]
will look at the spawns later on, since they are kinda off, but the boxes are there..

**Comment by dikkedeur** [comment]
i have looked on other databases as well and the spawnpositions are everywhere the same, since i cant find other data on if they are correctly spawned or not on alliance side im not changing it.
if more information will pop up i will again take a look at this one, for now i close this report.
