### ISSUE TITLE
[Quest][Ammen Vale] Rescue the Survivors!

### ISSUE THREAD

**Issue by YujiTFD** [Helios-Empire/Helios-Tracker#251]
Kind of bug: http://db.helios-empire.eu/?npc=16483

What bug do you encounter?: quest NPC (http://db.helios-empire.eu/?npc=16483) is not getting healed by required spell (http://db.helios-empire.eu/?spell=28880)

How to reproduce your bug?: Try and use http://db.helios-empire.eu/?spell=28880 for 

How it should work?: quest objective should be fulfilled with healing http://db.helios-empire.eu/?npc=16483 with http://db.helios-empire.eu/?spell=28880

**Comment by dikkedeur** [comment]
tested this, and indeed, but its not the quests thats bugged, its the spell.
when you use the spell the core doesnt check on if you select somebody or something in this case the npc or a friendly target.
so it casts always on the caster, thats the part that is wrong.
because you cast it always on yourself, you dont get cast credit.

**Comment by YujiTFD** [comment]
All right then, does means you know how to fix it or it's broken beyond repair?

I'm a TBC admirer since 2007 and just today joined Helios Empire because it's a PvE server, which I needed badly. Trying to be useful, will continue to contribute, also trying to lure more people in.
Thank you for your job! :)

**Comment by dikkedeur** [comment]
thanks for the heads up, basically everyting SHOULD and or CAN be fixed.. it depends on the time.
Im myself im not a c++ expert so i will forward this to Gladios and i have also forwarded it to OC.

**Comment by dikkedeur** [comment]
okay im a little bit further, its not the spell itself thats bugged, its the npc itself thats not receiving the cast in some way.

**Comment by dikkedeur** [comment]
Fixed
