### ISSUE TITLE
[Quest] [Blade's Edge Mountain] Test Flight: The Zephyrium Capacitorium

### ISSUE THREAD

**Issue by deeaz** [Helios-Empire/Helios-Tracker#254]
Kind of bug: http://db.helios-empire.eu/?quest=10557

What bug do you encounter?: Rally Zapnabber <Tally's Twin> ( http://db.helios-empire.eu/?npc=21461 ) Does not have any dialog to interact with you to complete quest 

How to reproduce your bug?: Start quest

How it should work?: Speak with Rally Zapnabber and use the Zephyrium Capacitorium. Return to Tally Zapnabber at Toshley's Station.

Operating System: W8.1

**Comment by dikkedeur** [comment]
will be fixed in next core update, also the upfollowing quests should be working now.
