### ISSUE TITLE
[Quest] [Blade's Edge Mountain] Test Flight: The Singing Ridge

### ISSUE THREAD

**Issue by deeaz** [Helios-Empire/Helios-Tracker#255]
Kind of bug: http://db.helios-empire.eu/?quest=10710)

What bug do you encounter?:Rally Zapnabber ( http://db.helios-empire.eu/?npc=21461 ) Does not have any dialog to interact with you to complete quest

How to reproduce your bug?: Start quest 

How it should work?: Sign Tally's Waiver, then speak with Rally Zapnabber to use the Zephyrium Capacitorium. Return to Tally Zapnabber at Toshley's Station.

Operating System: W8.1
- Please first search before making a new issue on our tracker.
- Please fill in above template to submit a new issue.
- Use always helios database links > http://db.helios-empire.eu to quests/npcs/spells etc.

**Comment by dikkedeur** [comment]
will be fixed in next core update.
