### ISSUE TITLE
[Quest][Starbreeze Village] The Emerald Dreamcatcher

### ISSUE THREAD

**Issue by YujiTFD** [Helios-Empire/Helios-Tracker#256]
Kind of bug: quest "The Emerald Dreamcatcher" (http://db.helios-empire.eu/?quest=2438)

What bug do you encounter?: it's not an actual bug, it's just requires tuning: timer for "Tallonkai's Dresser" (http://db.helios-empire.eu/?object=126158) is set for 5 (FIVE!) minutes after looting contained "Emerald Dreamcatcher" (http://db.helios-empire.eu/?item=8048). Our group of 3 spent 10 minutes idle waiting 2 dresser's respawns. And if there were a competition?

How to reproduce your bug?: loot "Emerald Dreamcatcher" (http://db.helios-empire.eu/?item=8048) from "Tallonkai's Dresser" (http://db.helios-empire.eu/?object=126158) and wait for it to respawn.

How it should work?: respawn timer should be within 5-10 seconds top.

**Comment by YujiTFD** [comment]
Basicly, ALL lootable containers have 5 minutes CD, it's insane.

**Comment by dikkedeur** [comment]
normally it is indeed, so we must make exceptions for such cases that you mention.

**Comment by dikkedeur** [comment]
fixed in next core update.
