### ISSUE TITLE
[Skill][Fishing] Fishing bobber stays in water even until after hooking.

### ISSUE THREAD

**Issue by YujiTFD** [Helios-Empire/Helios-Tracker#258]
Kind of bug: skill

What bug do you encounter?: when fishing, fishing bobber stays visible in water even until after hooking. You can spawn alot of bobbers, but when you move your character, they are all gone.
![wowscrnshot_051316_231432](https://cloud.githubusercontent.com/assets/19327740/15268610/c6d2fd7e-19ed-11e6-89bc-0a2f3b9b2a27.jpg)

How to reproduce your bug?: start fishing and bobbers will keep staying in water.

How it should work?: fishing bobber should disappear from water after hooking.

**Comment by dikkedeur** [comment]
https://github.com/Helios-Empire/Helios-Tracker/issues/180
