### ISSUE TITLE
Quest item/Chests

### ISSUE THREAD

**Issue by achelliez** [Helios-Empire/Helios-Tracker#26]
Many chests and Lootable quest items(such as serpentbloom WC quest) do not despawn after being looted,  Nor do they respawn, since they never despawn to begin with.

**Comment by Psychoz** [comment]
Confirm this. Very annoying

**Comment by dikkedeur** [comment]
we are working on a fix for this.

**Comment by dikkedeur** [comment]
it has been fixed..
