### ISSUE TITLE
[Quest][Darkshore] Plagued Lands

### ISSUE THREAD

**Issue by YujiTFD** [Helios-Empire/Helios-Tracker#260]
Kind of bug: Plagued Lands (http://db.helios-empire.eu/?quest=2118)

What bug do you encounter?: after being captured, hostile Rabid Thistle Bear (http://db.helios-empire.eu/?npc=2164) should turn into non-hostile Captured Rabid Thistle Bear (http://db.helios-empire.eu/?npc=11836) and follow player to the Tharnariun Treetender (http://db.helios-empire.eu/?npc=3701) in order to complete the quest. Captured Rabid Thistle Bear will not attack player, but will stay hostile and can be attacked, plus, quest gets completed immidiately. Also, leading it to the Darkshore make guards attack it, and it flees.
Quest is still completable, but rather confusing.

How to reproduce your bug?: set Tharnariun's Hope up (http://db.helios-empire.eu/?item=7586) and lure Rabid Thistle Bear (http://db.helios-empire.eu/?npc=2164) into walking over it.

How it should work?: Captured Rabid Thistle Bear should turn non-hostile (green) and quest should become complete after getting bear to the Auberdine.
![wowscrnshot_051416_171437](https://cloud.githubusercontent.com/assets/19327740/15268966/f7bd9a56-19f8-11e6-8c3a-4e5d7ca5e435.jpg)

**Comment by dikkedeur** [comment]
fixed in next core update, changed the faction of the captured thistle bear to neutral or friendly for that matter.. it will still register the script as completed when you capture the bear.. but for now this is the closest we can get.
