### ISSUE TITLE
Reputation vendors . Badge of justice vendor

### ISSUE THREAD

**Issue by flinta423** [Helios-Empire/Helios-Tracker#27]
Hello,

There is an issue with most likely all the main reputation vendors.

The issue is that they are selling PVP gear. Which shouldn't be availible at the vendors until a later time(later patch)

There is also an issue with the BoJ vendor in shattrath. You can purchase Nether vortex from him.

Thanks

// Flinta

**Comment by HEGladios** [comment]
What PvP gear are you referring to?

The Nether Vortex will be removed from the vendor as soon as possible.
It will be restored on patch 2.4.

**Comment by HEGladios** [comment]
Nether Vortex has been removed from the vendor.

**Comment by flinta423** [comment]
It's the rare pvp sets. Kodohide battlegear for example for druids.

requires honored reputation and some gold.

**Comment by HEGladios** [comment]
And when were they supposed to be added according to you? What patch?

**Comment by flinta423** [comment]
As far as I can remember it was added in the 2.4 patch.

**Comment by flinta423** [comment]
For information that should be correct.
http://www.mmo-champion.com/threads/604750-2-4-Test-realm-patch-notes?p=5545683&viewfull=1

2.4 Test realm patch notes
Reputation PvP sets
You can buy these sets from faction quartermasters if your reputation level is high enough.
Druid - Dragonhide Battlegear, Wyrmhide Battlegear, Kodohide Battlegear
Hunter - Stalker's Chain Battlegear
Mage - Evoker's Silk Battlegear
Paladin - Crusader's Scaled Battlegear, Crusader's Ornamented Battlegear
Priest - Satin Battlegear, Mooncloth Battlegear
Rogue - Opportunist's Battlegear
Shaman - Seer's Linked Battlegear, Seer's Mail Battlegear, Seer's Ringmail Battlegear
Warlock - Dreadweave Battlegear
Warrior - Savage's Plate Battlegear

**Comment by HEGladios** [comment]
Thanks for this! I was curious before launch whether these were supposed to be there or not, but I could not find any sources for when they were introduced.
I'll remove these from the vendors as soon as possible.

**Comment by HEGladios** [comment]
PvP gear has been removed from all the reputation vendors.
