### ISSUE TITLE
Feral Charge

### ISSUE THREAD

**Issue by blabsalot** [Helios-Empire/Helios-Tracker#31]
When Feral Charge is used the user charges to where the enemy was but, the enemy is moved to where the user was when they charged.

**Comment by HEGladios** [comment]
This is related to the other movement generator problems. We're working on fixing all of these issues.

**Comment by dikkedeur** [comment]
please retest, it should be fixed, but we need feedback on this one,

**Comment by HEGladios** [comment]
All movement related issues should be resolved now.
