### ISSUE TITLE
BC quest bug "Mission:Gateways Murketh and Shaadraz"

### ISSUE THREAD

**Issue by achelliez** [Helios-Empire/Helios-Tracker#32]
the bombing quest does not work at all, tried quite a few runs, and different bombing points.

**Comment by Pharzuph** [comment]
It looks like after 1 player does the quest, game sees the gates as Destroyed. My bro did the quest 10 sec before I went into the air and unlike him I was not able to complete quest.

**Comment by dikkedeur** [comment]
i tried it today, did it with multiple chars and it works, so cant reproduce.
howeer we are moving over to new scripting, so will change this to the new standards aswel.
