### ISSUE TITLE
[Quest] Hinott's Assistance

### ISSUE THREAD

**Issue by Psychoz** [Helios-Empire/Helios-Tracker#33]
qID 2480

After NPC says "Give me a few moments to examine the toxin..." he just walk through the walls up to the roof, so i cant reach him and finish the quest.
![wowscrnshot_081715_130726](https://cloud.githubusercontent.com/assets/13827887/9299748/00e690c6-44e1-11e5-89fd-d9bf570f23ab.jpg)

**Comment by dikkedeur** [comment]
again.... hmmm i spawned him yesterday since he was on the roof, and now he is there again..
hopefully he is only cleaning the chimney haha

**Comment by Psychoz** [comment]
Can you at least fix him at one spot? Or make this q automatically completed after takin'?

**Comment by dikkedeur** [comment]
already tried that... and the quest itself is autocompleted since when you talk he does something and then comes back and you can turn it in.. will look what we can do.

**Comment by dikkedeur** [comment]
i will look if i can change something as "hack" for the short term, since this is annoying for you guys.

**Comment by Psychoz** [comment]
Thanks forward. Rogues need poisons! Yarrr!

**Comment by dikkedeur** [comment]
hack fix incomming, 

i removed for now the pathing since that was messed up. so you can complete it now.
we will look into a more blizzlike way, but for now this one will do

**Comment by Psychoz** [comment]
Thanks!

**Comment by dikkedeur** [comment]
np

**Comment by dikkedeur** [comment]
fixed blizzlike on next core update.
