### ISSUE TITLE
Warrior Charge

### ISSUE THREAD

**Issue by ghost** [Helios-Empire/Helios-Tracker#4]
I just fell through the ground and under the world after I charged a mob.

**Comment by dikkedeur** [comment]
that can happen mostly when you charge something uphill right??
anyway, since you are here now, do you have a charname so i can port you?
or do you use the unstuck on the website?

**Comment by ghost** [comment]
Yes was a little hill.
I fell and my char got ported to the nearest graveyard by itself.

**Comment by dikkedeur** [comment]
Please retest, it should be fixed, but we need more feedback.

**Comment by HEGladios** [comment]
All movement related issues should be resolved now.
