### ISSUE TITLE
Spiritual Attunement mana return is too low

### ISSUE THREAD

**Issue by Enkindu** [Helios-Empire/Helios-Tracker#44]
Paladin Talent - Passive. 
From my experiences of tanking in Burning crusade as a paladin, the mana return from Spiritual attunement is too low.

**Comment by Enkindu** [comment]
Further analysis reveals that the mana regeneration is sporadic: 
Example: a heal for 432 only returned 4 mana, when it should be 4..*8 = 33 mana. 
Also, several mana 'gains' are not showing up on the Scrolling Combat Text.

This also appears related to the Seal / Judgement of wisdom also having sporadic non-granting of mana per proc.

**Comment by dikkedeur** [comment]
thanks for this detailed analysis!!!

**Comment by dikkedeur** [comment]
fixed some days ago
