### ISSUE TITLE
Paladin - Seal / Judgement of Wisdom PPM is low

### ISSUE THREAD

**Issue by Enkindu** [Helios-Empire/Helios-Tracker#45]
it appears that the PPM for judgement and seal of wisdom is low. Also, I have yet to see my seal and judgement proc at the same time when the debuff - judgement of wisdom is placed on the mob.

**Comment by dikkedeur** [comment]
did you close this by mistake Enkindu?

**Comment by Enkindu** [comment]
No, while I 'feel' the ppm rate is lower, I belive I need to perform a bit
more analysis prior to a ticker submission.

**Comment by dikkedeur** [comment]
okay when needed you can re-open it again.
