### ISSUE TITLE
The quest "Escape from Umbrafen" is bugged.

### ISSUE THREAD

**Issue by Helligg** [Helios-Empire/Helios-Tracker#47]
The mods that spawn are friendly, and she dissepears suddenly. After a few minutes the quest completed iteself, but with no help on my part other than starting it.

**Comment by ghost** [comment]
I did the quest earlier and the mobs were still friendly, but she did not despawn, just ran at mount speed all the way until the quest showed completed.

**Comment by dikkedeur** [comment]
did had this problem, just tested it and everything was working as it should.

so i mark this as closed.
