### ISSUE TITLE
Berserker stance quest; The Affray

### ISSUE THREAD

**Issue by drakulf** [Helios-Empire/Helios-Tracker#49]
Im having issues with the quest The Affray in warrior quest chain for berserker stance. The objective is to stand in the middle of the crowd and one of the NPCs will call out challengers for the warrior to defeat. When I get to the middle, nothing happens.

**Comment by dikkedeur** [comment]
i have just tested this on a fresh warrior, and was able to do the quest without any problems.
timer and everything works as intended.
