### ISSUE TITLE
Mob Aggro Range

### ISSUE THREAD

**Issue by ghost** [Helios-Empire/Helios-Tracker#5]
The mobs just aggro from too far away, it is really insane. You bodypull even gray mobs from far away. You charge a mob and 3 other mobs which stand faaar away run towards you.

**Comment by dikkedeur** [comment]
thanks for the report, we have adjusted it a little bit.
we keep on monitoring this, if it gets out of hand we can always change it bit by bit.

**Comment by ghost** [comment]
Great. :)

**Comment by HEGladios** [comment]
I think the aggro range was always very high in TBC.

**Comment by ghost** [comment]
But not that high, you can't even run further around green mobs without them seeing you.

**Comment by dikkedeur** [comment]
i havent got any report back that it is still bad, so mark this one as fixed.
