### ISSUE TITLE
Mission: The Abyssal Shelf isnt working

### ISSUE THREAD

**Issue by Dryda** [Helios-Empire/Helios-Tracker#60]
I can start the quest and i can do everything i have to do, but though the quest is "finished" in the quest log the NPC "Forward Commander To'arch" has still a grey questionmark above his head what means im not able to go on. (Thats pretty bad because i cant start the mag'har quests if i cant finish this one)

**Comment by HEGladios** [comment]
This quest is fixed! For it to work you have to first abandon the quest and retake it.
