### ISSUE TITLE
Warlock pet Voidcaller Consume Shadows bug

### ISSUE THREAD

**Issue by Hikari228** [Helios-Empire/Helios-Tracker#64]
the spell doesnt work. I try to click it out of combat and the voidcaller tries to channel but then stops right after.

**Comment by ghost** [comment]
This bug still seems to be happening,as a quick update. The pet does seem to increase his healing after i use the rank 6 version but not anywhere near the amount as stated in the detail, he does however do the affect of shadows surrounding him.

**Comment by HEGladios** [comment]
Duplicate: #62
