### ISSUE TITLE
Quest in Hellfire Penisula

### ISSUE THREAD

**Issue by Hikari228** [Helios-Empire/Helios-Tracker#65]
Gateways Murketh and Shaadraz. the wyvern flies a little fast and you do not get credit for hitting the gateways.

**Comment by dikkedeur** [comment]
most of the time if i recall from players reports it is due another player that has done the quest so the gateways get destroyed and marked and keeps on being in that state.

in other words, the script keeps on hanging.

**Comment by dikkedeur** [comment]
fixed in next core update
