### ISSUE TITLE
Thrallmar Hellfire Citidale Heroic Key 

### ISSUE THREAD

**Issue by Hikari228** [Helios-Empire/Helios-Tracker#68]
The key is buyable at honored not revered

**Comment by HEGladios** [comment]
![thrallmar key](https://cloud.githubusercontent.com/assets/11843403/9364721/126cb3ba-46ae-11e5-9bb7-0fe883704414.PNG)

Did you actually manage to buy the key, or was it just visual?
If it's visual then simply clear your cache :)

**Comment by Hikari228** [comment]
I havnt tried to buy it since im not honored. When I am ill try it.

**Comment by dikkedeur** [comment]
this is not bugged, since i was not able to buy it while being honored, when i was revered i wa able to buy.
so works as intended
