### ISSUE TITLE
Quest: Finding the Survivors

### ISSUE THREAD

**Issue by Urbb** [Helios-Empire/Helios-Tracker#69]
Freeing Mag'har prisoners is not registered towards quest completion. (The quest cannot be completed since the action/objective required is not registered.)

**Comment by scottiedog321** [comment]
I had the same issue. Freeing prisoners did not count toward progression.

**Comment by Hikari228** [comment]
not to mention the key drops are so bad

**Comment by Bloobeary** [comment]
This quest is still bugged. The droprate of the keys is extremely low and opening the cages doesn't register towards quest completion.

**Comment by dikkedeur** [comment]
Will be working on next core update.

The droprate of the key is 10% as you can see on our database..
http://db.helios-empire.eu/?item=25604

when you see on wowhead
http://www.wowhead.com/item=25604/warmaul-prison-key#comments
everybody is complaining about the poor droprate, so in fact is a blizz factor that the key is low on droprate, on wowhead it even says 5%

anyway, FIXED!!!!
