### ISSUE TITLE
Mobs not attacking when being attacked

### ISSUE THREAD

**Issue by ghost** [Helios-Empire/Helios-Tracker#7]
Some defias mobs (Defias Smuggler, Defias, Trapper, etc.) in Westfall don't attack you and just stand there or still walk even though you hit them.

**Comment by ghost** [comment]
Okay seems to be an issue with a lot of mobs, not just the defias mobs in Westfall. I'm currently questing in Redridge Mountains and there it happens too.

**Comment by dikkedeur** [comment]
what class are you??
do you first hit them with a spell or how to reproduce?? do you see a pattern?

**Comment by ghost** [comment]
I'm a warrior and my mate is a mage. It doesn't matter if I charge the mob or just run up to it and attack it or if my mate frostbolts the mob. We encountered this issue like I said in Westfall with the Defias mobs and in Redridge Mountains with the Gnolls. It is random which mob won't attack and which attacks.

**Comment by HEGladios** [comment]
I'll look into this.

**Comment by ghost** [comment]
Here are the coords for the Gnolls (Redridge Brute, Redridge Mystic) in Redridge Mountains where we entcountered this issue: 39:33
and for the Defias (Defias Smuggler, Defias Trapper) in Westfall: 46:39

**Comment by Sleekcrush** [comment]
Happening with any types of mobs that I have run into at multiple locations. Does not happen to every mob in the area. (Horde locations - Durotar, Barrens, etc.)

**Comment by dikkedeur** [comment]
seems fixed at least for me.
