### ISSUE TITLE
Hellfire ramparts ( normal)

### ISSUE THREAD

**Issue by Helligg** [Helios-Empire/Helios-Tracker#70]
Its waay undertooned, The mobs bearly do any damage. Hitting a lvl 67 tank for 50-150 damage.

Alot of the packs are missing .

The 1st boss does not patrol, and one add is missing. He also does way to little damage on mellee hits. 

2nd boss bearly does any damage to tank. 

3rd boss dragon and orc spawn at the same time. 

Again undertoned. Bearly a need for a healer.

**Comment by HEGladios** [comment]
Hellfire Ramparts has been completely revamped. All spawns and patrols are nearly blizzlike and damage has been corrected.
