### ISSUE TITLE
Corpses (with loot) despawns way to quickly

### ISSUE THREAD

**Issue by Helligg** [Helios-Empire/Helios-Tracker#71]
Killed mobs despawn to quickly. So loot is lost. Same for bosses.

**Comment by HEGladios** [comment]
Wasn't it only until WotLK that blizzard improved this?
(Even so, I'm still willing to look into it, for convenience sake.)

**Comment by dikkedeur** [comment]
helligg can you say how long it takes before mobs despawn??

**Comment by ghost** [comment]
I've noticed while killing more than one mob the corpses will despawn before i'm able to loot them, the exact amount of time will vary. I've actually noticed it mainly when fighting the monsters around "The Bone Wastes" and south of "Auchindoun" If I pull 3 or more mobs by the time combat ends whether it be killing the mobs or running away after killing two, the bodies will despawn before i'm able to loot, I'd say within about 1 minute of death.

**Comment by dikkedeur** [comment]
should be fixed, increased it with 2x
