### ISSUE TITLE
Spell: Grounding Totem

### ISSUE THREAD

**Issue by Urbb** [Helios-Empire/Helios-Tracker#72]
The spell does not work properly because the player still takes the damage that should be soaked by the totem. (Note: Only tested against npcs.) The animation for this spell/totem is right, since the opponents spell animation is drawn to the Grounding Totem, but the damage is still taken by the player.

**Comment by HEGladios** [comment]
Using this issue: https://github.com/Helios-Empire/Helios-Tracker/issues/178
