### ISSUE TITLE
Subzone: Sunspring Post (Nagrand)

### ISSUE THREAD

**Issue by Urbb** [Helios-Empire/Helios-Tracker#73]
This area has way too few mobs, the place should have been swarming with them (especially Murkblood Scavengers). I came to this subzone fresh, and found the place almost deserted by mobs. After taking a lap I found about six or so Murkblood Scavengers and about the same amount in Murkblood Raiders, and this is too few since the objective for the quest quest [Once Were Warriors] is to kill 20 Murkblood Raiders and 40 Murkblood Scavengers, and the objective of the quest [Vile Idolatry] is to loot 20 Murkblood Idol.

**Comment by dikkedeur** [comment]
compared to TC database there are indeed to less of the mobs you mention, it are 7 where there should be according to TC 17 of them..

**Comment by HEguinness** [comment]
Shouldn't this be fixable just by spawning creatures from a GM account? it should add them permanently to the database.

**Comment by dikkedeur** [comment]
that can be, but i want to take tc spawnpoints..so i will do that in a few hours :+1:

**Comment by dikkedeur** [comment]
didnt got time yet, since i was redoing razorfen kraul.. and it took more time then i thought :+1: 
not to mention you cant directly take spawns from tc to our database since columns are off.

**Comment by Bloobeary** [comment]
I can confirm as well. Not enough spawns and that makes doing these quests a lot longer than it should.
Once we were Warriors: http://db.helios-empire.eu/?quest=9865
Murkblood Corrupters: http://db.helios-empire.eu/?quest=9862

This one that happens in the same region is still doable reasonably fast, though. Vile Idolatry: http://db.helios-empire.eu/?quest=9863

**Comment by dikkedeur** [comment]
fixed spawns on next core update
