### ISSUE TITLE
Quest: Draenei Paladin Redemption

### ISSUE THREAD

**Issue by Veldrin666** [Helios-Empire/Helios-Tracker#74]
After accepting the quest, I have found the NPC that is to be resurrected where it needs to be but alive and it couldn't be targeted by the "Symbol of Life" quest-item. Over the course of one day, I repeatedly (three or four times) checked on the NPC and its status didn't change during this time, which resulted in me posting a ticket - the quest was auto-completed for me by a GM but the bug remains.

**Comment by dikkedeur** [comment]
confirmed.

**Comment by dikkedeur** [comment]
is fixed some time ago...
