### ISSUE TITLE
Arcane Torrent Blood Elf Passive

### ISSUE THREAD

**Issue by Hikari228** [Helios-Empire/Helios-Tracker#75]
its bugged and does not give mana when used.

**Comment by HEGladios** [comment]
You have to cast Mana Tap first if you want to get mana from Arcane Torrent.

**Comment by Hikari228** [comment]
i know, i do and it doesnt consume the stacks

**Comment by Hikari228** [comment]
I can show you ingame if you like?

**Comment by dikkedeur** [comment]
tried it ingame and works as intended, when you have mana tap active to a max of 3, you gain for every mana tab 10 mana when using arcane torrent.
i dont see a bug here.
