### ISSUE TITLE
Quest: Standards and Practices (in Nagrand)

### ISSUE THREAD

**Issue by Urbb** [Helios-Empire/Helios-Tracker#76]
The quest can't be completed because the second and third Battle Standard cannot be placed at the objective location. Trying to place the standard at the second and third Burning Blade Pyres fails because "Requires Burning Blade pyre in the Burning Blade Ruins."

**Comment by scottiedog321** [comment]
I had the same problem. 1st pyre works okay, 2nd and 3rd are broken.

**Comment by dikkedeur** [comment]
will be fixed in next core update
