### ISSUE TITLE
Last Boss in Hellfire Ramparts

### ISSUE THREAD

**Issue by Hikari228** [Helios-Empire/Helios-Tracker#77]
I am a Demonology Warlock. My felguard was my pet during the boss. He bugged and ran around attacking my party.

**Comment by Enkindu** [comment]
I think a more apt use of this ticket is to state that Nazen is not flying around: instead, the,dragon opts to stay on the ground and can  melee attack (if targets are available, and cast fireballs. He also moves much faster then intended, thus enabling the dragon to cast more often.

**Comment by Hikari228** [comment]
this has nothing to do with the dragon. it has everything to do with my felguard attack my party.

**Comment by HEGladios** [comment]
Boss fight works fine now, closing this issue.
