### ISSUE TITLE
Death Bug in Pools of Aggonar

### ISSUE THREAD

**Issue by Hikari228** [Helios-Empire/Helios-Tracker#78]
So I was farming some slimes in the area. I happened to die. My pet however didnt despawn. I clicked release nothing happened. I am dead but cant release but mobs agroed like i was alive. But i am skill gaining defense points. Odd bug.

**Comment by HEGladios** [comment]
Have not encountered this while questing in the Pools of Aggonar.

**Comment by Absolution2015** [comment]
Please confirm whether this is still happening.

**Comment by HEGladios** [comment]
Closing this. If anyone runs into this issue, comment here with more details.
I'm guessing this is related to a similar bug where certain activated items can cause this behavior if you die while the effect is active.
