### ISSUE TITLE
Underwater Swimming / Swimming up Issue

### ISSUE THREAD

**Issue by Sleekcrush** [Helios-Empire/Helios-Tracker#8]
When underwater, pressing the space bar makes you jump instead of swimming up.

I know this is a minor issue, but consider fixing this.

**Comment by ghost** [comment]
I think that was the case in TBC, they changed it in Wotlk or something. But not sure.

**Comment by dikkedeur** [comment]
This is normal for patch 2.4.3

i know its strange, i even found it a bug.. but its fixed in wotlk :+1:
