### ISSUE TITLE
Mobs are able to cast channeled spells while running

### ISSUE THREAD

**Issue by Enkindu** [Helios-Empire/Helios-Tracker#80]
In Hellfire Peninsula, Bonechewer Evokers were casting Fireball while running away in panic status due to low health. This should not happen as it is a channeled spell.

**Comment by Enkindu** [comment]
I wish to clarify terminology used. Channeled should instead be spells that have a cast timer or non-instant cast spells.  (E.g. fireball is not the  same as mind flay).

**Comment by dikkedeur** [comment]
was not able to get same result, in the meantime it can be that it was fixed or it was a glitch that was temp.
