### ISSUE TITLE
Quest:  [To Legion Hold]

### ISSUE THREAD

**Issue by Shillex** [Helios-Empire/Helios-Tracker#83]
Quest  [To Legion Hold] 
http://wowwiki.wikia.com/wiki/Quest:To_Legion_Hold_%28Horde%29  is broken.
You should come to the peak of the Legion hold, use quest items that turns you to the box, and then listen dialogue between 2 demons, after that it should be completed.

But after the listening the demons speech nothing happens, killing the demon is not gives you anything.

This quest is a part of the huge quest chain that gives a nice xp\gold and good pre-raid rings.

**Comment by dikkedeur** [comment]
Will be fixed in next core update
