### ISSUE TITLE
Bugged quest causes server crash

### ISSUE THREAD

**Issue by Inyu** [Helios-Empire/Helios-Tracker#85]
i think the quest "The Seers's Relic" crashes the server no real proof tho.
I tried it three times and the server crashed at the exact same time in the quest.

**Comment by dikkedeur** [comment]
yup the crashlogs show that that is indeed the cause. thanks for letting us know,

**Comment by HEGladios** [comment]
Crash will be fixed after next core update. Quest may still not function properly, which will need a separate report.
