### ISSUE TITLE
Quest "HELP!" in Nagrand

### ISSUE THREAD

**Issue by Inyu** [Helios-Empire/Helios-Tracker#86]
The quest "HELP!" doesn't work. You can get the key and open the cage but the quest is not completed.

**Comment by dikkedeur** [comment]
Fixed on next core update.

**Comment by deeaz** [comment]
Quest is still bugged as of March 11 2016

**Comment by dikkedeur** [comment]
a newer update broke my fix, i will look into it as soon as possible then.

**Comment by dikkedeur** [comment]
fixed in next core update..
