### ISSUE TITLE
Quest: The Vengeful Harbinger

### ISSUE THREAD

**Issue by scottiedog321** [Helios-Empire/Helios-Tracker#87]
I'm going to copy+paste from the Feenix github, because it had the same exact issue:

---

The quest item "Draenei Tomb Relic" does not summon the "Draenei Tomb Guardian" that is required for the event to start. The item is usable (And the cooldown will be burned once the item is used), but nothing is spawned. Therefore, the quest cannot be completed.

To reproduce:
1. Obtain the quest
2. Make it to the tomb in north east Bone Wastes
3. Get to the crypt with the floating Draenei ghost
4. Use the quest item

Quest: http://wow.gamepressure.com/quest.asp?ID=3575

---

Their resolution was to replace it with this: http://wowwiki.wikia.com/wiki/Quest:Vengeful_Souls

Source: https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/240

**Comment by dikkedeur** [comment]
will be done on next core update. we did indeed now replace it with the quest vengeful souls as of patch 3.2. it seems that even blizz was tired of that quest being bugged on their servers and did replace it because of that reason.
