### ISSUE TITLE
Quest: Missing Friends

### ISSUE THREAD

**Issue by scottiedog321** [Helios-Empire/Helios-Tracker#88]
During the quest, you should be able to release multiple children from the cages at the same time. Currently, only one child is released regardless of how many are in the cage.

Quest: http://wowwiki.wikia.com/wiki/Quest:Missing_Friends

How it should work: https://www.youtube.com/watch?v=btuziCmMN9s

edit:
The Captive Children also don't seem to be respawning. Saw one just hanging out in the middle of no where, might have something to do with it.

http://i.imgur.com/L2lpu1x.jpg

**Comment by dikkedeur** [comment]
strange indeed that they are not respawning, since thats the problem, they are spawned inside the cages and everything works..
i spawn new one, same problem, they dont respawn...

**Comment by HEGladios** [comment]
@HEGuinness please take a look.

**Comment by dikkedeur** [comment]
will be fixed in next core update..
respawning the childs are fixed, along with thank you text when you free them.
