### ISSUE TITLE
Quest: What Book? I Don't See Any Book.

### ISSUE THREAD

**Issue by scottiedog321** [Helios-Empire/Helios-Tracker#91]
I talk to "Dirty" Larry, and he doesn't do anything.
Should work like this: https://www.youtube.com/watch?v=6n5fyOh9jBg

**Comment by dikkedeur** [comment]
hmmm, suddenly after core update and restart this quest does work.
so when it doesnt work or is stuck, it might need a restart of core..
strange..
but its not bugged since well now it works, tested 4 times.

**Comment by dikkedeur** [comment]
sidenote: after somebody does the quest the npc is stuck in script, gms need to kill and respawn it to make script active again...

word a look at it.

**Comment by dikkedeur** [comment]
fixed
