### ISSUE TITLE
Quest: Who Are They? (Horde)

### ISSUE THREAD

**Issue by scottiedog321** [Helios-Empire/Helios-Tracker#92]
Scout Neftis does not cast the disguise when accepting the quest, nor does she give the option to get the disguise.

http://i.imgur.com/JY9ioZN.jpg

https://www.youtube.com/watch?v=qjitwawKEOE (NOTE: Not getting the disguise while mounted IS PER RETAIL)

http://www.wowhead.com/quest=10041/who-are-they

**Comment by Jucamilo** [comment]
I completed this quest, just going in and killing the 3 guys that i was supposed to speak with :D

**Comment by Absolution2015** [comment]
So is this still happening?

**Comment by dikkedeur** [comment]
still bugged, tested it a few days ago abs :+1:

**Comment by dikkedeur** [comment]
Will be fixed in NEXT core update if all goes well, on our dev server i have it running right now, private weeks for alliance is giving the disguise and also scout neftis, so fixed for both factions.
