### ISSUE TITLE
Missing Aldor Quests on Neutral Rep[0/3000]

### ISSUE THREAD

**Issue by Pharzuph** [Helios-Empire/Helios-Tracker#94]
Once I did quest in Shattrath City that leads to picking Aldor or Scryer,  I did not get the quest that sends me to Aldor Rise. I am Neutral with Aldor[0/3000] but I am not able to pick up [R] quests for Mark of Kil'jaeden. Only quest that I am able to pick up in Aldor Rise is one the is sending me to Isle of Quel'Danas, also as I recall I should be able to pick up quest in Aldor bank that sends me to Netherstorm[Area 52]. Is this general issue or is it only me?

P.S. I am Blood Elf, is there a chance that this is causing the problem ?

This is the list of [R] quests that I should have on neutral Rep
![aldor](https://cloud.githubusercontent.com/assets/13841110/9433434/328ea120-4a33-11e5-8519-41280cdcba90.png)
But, from some reason I can't get any of those.

**Comment by dikkedeur** [comment]
should be fixed now, please clear your cache.
