### ISSUE TITLE
Quest : [Against the Legion] in Netherstorm

### ISSUE THREAD

**Issue by Pharzuph** [Helios-Empire/Helios-Tracker#99]
Quest stats in Nagrand and leads to Netherstorm where You need to kill Wrath Priestess that has around 25% chase to drop [Freshly Drawn Blood] that is after that used to summon Avatar of Sathal.

So the issue is that after killing around 20 of them I still did not get the Blood, this might be my really bad RNG but still with that drop chase not to get it after so many kills looks like loot table of the mob is messed.

**Comment by dikkedeur** [comment]
found the problem, in the database it says it needs to drop if you have a quest active, but the item is NOT even needed for a quest.
so i will change the droprate to blizzlike values and that is around 25%

**Comment by dikkedeur** [comment]
After killing 5 times it dropped.

![schermafbeelding 2015-08-26 om 12 49 24](https://cloud.githubusercontent.com/assets/11842306/9491657/fa547fc2-4bf0-11e5-8948-d72da4f7e64c.png)
